/**
 * Yuco Messenger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AxiosInstance } from 'axios';
import { AttachmentApiInterface } from './api/attachment-api';
import { ChatApiInterface } from './api/chat-api';
import { DefaultApiInterface } from './api/default-api';
import { LinkPreviewApiInterface } from './api/link-preview-api';
import { MessageApiInterface } from './api/message-api';
import { WebSocketCallbackApiInterface } from './api/web-socket-callback-api';
export interface YucoMessengerApiGetterInterface {
    getAttachmentApi: () => AttachmentApiInterface;
    getChatApi: () => ChatApiInterface;
    getDefaultApi: () => DefaultApiInterface;
    getLinkPreviewApi: () => LinkPreviewApiInterface;
    getMessageApi: () => MessageApiInterface;
    getWebSocketCallbackApi: () => WebSocketCallbackApiInterface;
}
export declare const yucoMessengerConfigureGetter: (applyInterceptors: <T>(apiCreator: (axios: AxiosInstance) => T) => T) => YucoMessengerApiGetterInterface;
