/**
 * Yuco Messenger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { MSFullChat } from './msfull-chat';
/**
 *
 * @export
 * @interface MSChatList
 */
export interface MSChatList {
    /**
     *
     * @type {Array<MSFullChat>}
     * @memberof MSChatList
     */
    chats: Array<MSFullChat>;
    /**
     *
     * @type {{ [key: string]: object; }}
     * @memberof MSChatList
     */
    accounts: {
        [key: string]: object;
    };
}
