/**
 * Yuco Messenger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Chat } from './chat';
import type { MSBulkMessage } from './msbulk-message';
import type { MSChatDirectory } from './mschat-directory';
import type { SchemasModelsChatSubSchemaMutePeriod } from './schemas-models-chat-sub-schema-mute-period';
/**
 *
 * @export
 * @interface MSFullChat
 */
export interface MSFullChat {
    /**
     *
     * @type {SchemasModelsChatSubSchemaMutePeriod}
     * @memberof MSFullChat
     */
    mute?: SchemasModelsChatSubSchemaMutePeriod;
    /**
     *
     * @type {number}
     * @memberof MSFullChat
     */
    count_unread_messages?: number;
    /**
     *
     * @type {string}
     * @memberof MSFullChat
     */
    role: MSFullChatRoleEnum;
    /**
     *
     * @type {Array<MSBulkMessage>}
     * @memberof MSFullChat
     */
    pinned_messages?: Array<MSBulkMessage>;
    /**
     *
     * @type {Array<MSChatDirectory>}
     * @memberof MSFullChat
     */
    folders?: Array<MSChatDirectory>;
    /**
     *
     * @type {Array<MSBulkMessage>}
     * @memberof MSFullChat
     */
    messages?: Array<MSBulkMessage>;
    /**
     *
     * @type {MSBulkMessage}
     * @memberof MSFullChat
     */
    message?: MSBulkMessage;
    /**
     *
     * @type {string}
     * @memberof MSFullChat
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof MSFullChat
     */
    uuid: string;
    /**
     *
     * @type {string}
     * @memberof MSFullChat
     */
    icon_hashname?: string;
    /**
     *
     * @type {string}
     * @memberof MSFullChat
     */
    created_at: string;
    /**
     *
     * @type {string}
     * @memberof MSFullChat
     */
    updated_at: string;
    /**
     *
     * @type {Chat}
     * @memberof MSFullChat
     */
    type: Chat;
}
export declare const MSFullChatRoleEnum: {
    readonly Owner: "owner";
    readonly Member: "member";
    readonly Admin: "admin";
};
export type MSFullChatRoleEnum = (typeof MSFullChatRoleEnum)[keyof typeof MSFullChatRoleEnum];
