/**
 * Yuco Messenger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { MSAttachment } from './msattachment';
import type { MSUser } from './msuser';
/**
 *
 * @export
 * @interface SourceMessage1
 */
export interface SourceMessage1 {
    /**
     *
     * @type {MSUser}
     * @memberof SourceMessage1
     */
    sender?: MSUser;
    /**
     *
     * @type {Array<MSAttachment>}
     * @memberof SourceMessage1
     */
    attachments?: Array<MSAttachment>;
    /**
     *
     * @type {string}
     * @memberof SourceMessage1
     */
    uuid: string;
    /**
     *
     * @type {boolean}
     * @memberof SourceMessage1
     */
    edited: boolean;
    /**
     *
     * @type {string}
     * @memberof SourceMessage1
     */
    cache_id: string;
    /**
     *
     * @type {string}
     * @memberof SourceMessage1
     */
    message?: string;
    /**
     *
     * @type {string}
     * @memberof SourceMessage1
     */
    account_uuid: string;
    /**
     *
     * @type {number}
     * @memberof SourceMessage1
     */
    object_uuid?: number;
    /**
     *
     * @type {string}
     * @memberof SourceMessage1
     */
    object_type?: string;
    /**
     *
     * @type {string}
     * @memberof SourceMessage1
     */
    created_at: string;
    /**
     *
     * @type {string}
     * @memberof SourceMessage1
     */
    updated_at: string;
    /**
     *
     * @type {string}
     * @memberof SourceMessage1
     */
    deleted_at?: string;
    /**
     *
     * @type {string}
     * @memberof SourceMessage1
     */
    chat_uuid: string;
    /**
     *
     * @type {string}
     * @memberof SourceMessage1
     */
    fw_source_message?: string;
    /**
     *
     * @type {string}
     * @memberof SourceMessage1
     */
    fw_source_account_uuid?: string;
}
