/**
 * YUCO Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AxiosConfiguration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import { type RequestArgs, BaseAPI } from '../base';
import type { SJBConnectRequest } from '../model';
/**
 * WebSocketApi - axios parameter creator
 * @export
 */
export declare const WebSocketApiAxiosParamCreator: (configuration?: AxiosConfiguration) => {
    /**
     *
     * @summary Connect
     * @param {SJBConnectRequest} sJBConnectRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    connectPost: (sJBConnectRequest: SJBConnectRequest, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * WebSocketApi - functional programming interface
 * @export
 */
export declare const WebSocketApiFp: (configuration?: AxiosConfiguration) => {
    /**
     *
     * @summary Connect
     * @param {SJBConnectRequest} sJBConnectRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    connectPost(sJBConnectRequest: SJBConnectRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
};
/**
 * Request parameters for connectPost operation in WebSocketApi.
 * @export
 * @interface WebSocketApiConnectPostRequest
 */
export interface WebSocketApiConnectPostRequest {
    /**
     *
     * @type {SJBConnectRequest}
     * @memberof WebSocketApiConnectPost
     */
    readonly sJBConnectRequest: SJBConnectRequest;
}
/**
 * WebSocketApi - interface
 * @export
 * @interface WebSocketApi
 */
export interface WebSocketApiInterface {
    /**
     *
     * @summary Connect
     * @param {SJBConnectRequest} sJBConnectRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebSocketApiInterface
     */
    connectPost(requestParameters: WebSocketApiConnectPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<object>;
}
/**
 * WebSocketApi - object-oriented interface
 * @export
 * @class WebSocketApi
 * @extends {BaseAPI}
 */
export declare class WebSocketApi extends BaseAPI implements WebSocketApiInterface {
    /**
     *
     * @summary Connect
     * @param {WebSocketApiConnectPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebSocketApi
     */
    connectPost(requestParameters: WebSocketApiConnectPostRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any>>;
}
