import '@ionic/react/css/core.css';
import '@ionic/react/css/normalize.css';
import '@ionic/react/css/structure.css';
import '@ionic/react/css/typography.css';
import '@ionic/react/css/padding.css';
import '@ionic/react/css/float-elements.css';
import '@ionic/react/css/text-alignment.css';
import '@ionic/react/css/text-transformation.css';
import '@ionic/react/css/flex-utils.css';
import '@ionic/react/css/display.css';
import './styles/variables.css';
import './styles/custom-variables.css';
import './styles/global-fonts.scss';
import './styles/global-fonts-full.scss';
import '@ionic/react/css/ionic-swiper.css';
import { FC } from 'react';
import { IMessengerApp } from './types';
declare const App: FC<IMessengerApp>;
export default App;
