/**
 * YUCO Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AxiosInstance } from 'axios';
import { DefaultApiInterface } from './api/default-api';
import { PrivateApiInterface } from './api/private-api';
import { WebSocketApiInterface } from './api/web-socket-api';
export interface YUCOAuthApiGetterInterface {
    getDefaultApi: () => DefaultApiInterface;
    getPrivateApi: () => PrivateApiInterface;
    getWebSocketApi: () => WebSocketApiInterface;
}
export declare const yUCOAuthConfigureGetter: (applyInterceptors: <T>(apiCreator: (axios: AxiosInstance) => T) => T) => YUCOAuthApiGetterInterface;
