/**
 * Yuco Messenger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AxiosConfiguration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import { type RequestArgs, BaseAPI } from '../base';
import type { LinkSchema } from '../model';
/**
 * LinkPreviewApi - axios parameter creator
 * @export
 */
export declare const LinkPreviewApiAxiosParamCreator: (configuration?: AxiosConfiguration) => {
    /**
     *
     * @summary Create Links
     * @param {LinkSchema} linkSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createLinksPost: (linkSchema: LinkSchema, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * LinkPreviewApi - functional programming interface
 * @export
 */
export declare const LinkPreviewApiFp: (configuration?: AxiosConfiguration) => {
    /**
     *
     * @summary Create Links
     * @param {LinkSchema} linkSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createLinksPost(linkSchema: LinkSchema, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * Request parameters for createLinksPost operation in LinkPreviewApi.
 * @export
 * @interface LinkPreviewApiCreateLinksPostRequest
 */
export interface LinkPreviewApiCreateLinksPostRequest {
    /**
     *
     * @type {LinkSchema}
     * @memberof LinkPreviewApiCreateLinksPost
     */
    readonly linkSchema: LinkSchema;
}
/**
 * LinkPreviewApi - interface
 * @export
 * @interface LinkPreviewApi
 */
export interface LinkPreviewApiInterface {
    /**
     *
     * @summary Create Links
     * @param {LinkSchema} linkSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LinkPreviewApiInterface
     */
    createLinksPost(requestParameters: LinkPreviewApiCreateLinksPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;
}
/**
 * LinkPreviewApi - object-oriented interface
 * @export
 * @class LinkPreviewApi
 * @extends {BaseAPI}
 */
export declare class LinkPreviewApi extends BaseAPI implements LinkPreviewApiInterface {
    /**
     *
     * @summary Create Links
     * @param {LinkPreviewApiCreateLinksPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LinkPreviewApi
     */
    createLinksPost(requestParameters: LinkPreviewApiCreateLinksPostRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any>>;
}
