/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * An enumeration.
 * @export
 * @enum {string}
 */
export declare const AdvertisingObject: {
    readonly Account: "ACCOUNT";
    readonly WebSite: "web_site";
    readonly MobileApp: "mobile_app";
    readonly ServicesAndGoods: "services_and_goods";
};
export type AdvertisingObject = (typeof AdvertisingObject)[keyof typeof AdvertisingObject];
