/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { LegalStatusChoices } from './legal-status-choices';
/**
 *
 * @export
 * @interface AdvertisementProfileUpdateSchema
 */
export interface AdvertisementProfileUpdateSchema {
    /**
     *
     * @type {string}
     * @memberof AdvertisementProfileUpdateSchema
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof AdvertisementProfileUpdateSchema
     */
    surname?: string;
    /**
     *
     * @type {string}
     * @memberof AdvertisementProfileUpdateSchema
     */
    patronymic?: string;
    /**
     *
     * @type {string}
     * @memberof AdvertisementProfileUpdateSchema
     */
    email?: string;
    /**
     *
     * @type {number}
     * @memberof AdvertisementProfileUpdateSchema
     */
    timezone_id?: number;
    /**
     *
     * @type {string}
     * @memberof AdvertisementProfileUpdateSchema
     */
    company?: string;
    /**
     *
     * @type {LegalStatusChoices}
     * @memberof AdvertisementProfileUpdateSchema
     */
    legal_status?: LegalStatusChoices;
    /**
     *
     * @type {string}
     * @memberof AdvertisementProfileUpdateSchema
     */
    type?: string;
}
