/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { GroupPosition } from './group-position';
import type { PriceType } from './price-type';
/**
 *
 * @export
 * @interface AdvertisementGroupCreateSchema
 */
export interface AdvertisementGroupCreateSchema {
    /**
     *
     * @type {number}
     * @memberof AdvertisementGroupCreateSchema
     */
    campaign_id: number;
    /**
     *
     * @type {number}
     * @memberof AdvertisementGroupCreateSchema
     */
    audience_id: number;
    /**
     *
     * @type {string}
     * @memberof AdvertisementGroupCreateSchema
     */
    name: string;
    /**
     *
     * @type {GroupPosition}
     * @memberof AdvertisementGroupCreateSchema
     */
    position: GroupPosition;
    /**
     *
     * @type {PriceType}
     * @memberof AdvertisementGroupCreateSchema
     */
    price_type: PriceType;
    /**
     *
     * @type {number}
     * @memberof AdvertisementGroupCreateSchema
     */
    price: number;
    /**
     *
     * @type {number}
     * @memberof AdvertisementGroupCreateSchema
     */
    budget_constraint: number;
    /**
     *
     * @type {string}
     * @memberof AdvertisementGroupCreateSchema
     */
    run_time_start: string;
    /**
     *
     * @type {string}
     * @memberof AdvertisementGroupCreateSchema
     */
    run_time_end: string;
}
