/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CampaignGoal } from './campaign-goal';
/**
 *
 * @export
 * @interface CampaignGoalSchema
 */
export interface CampaignGoalSchema {
    /**
     *
     * @type {string}
     * @memberof CampaignGoalSchema
     */
    'name': string;
    /**
     *
     * @type {CampaignGoal}
     * @memberof CampaignGoalSchema
     */
    'value': CampaignGoal;
}
