/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * An enumeration.
 * @export
 * @enum {string}
 */
export declare const CampaignStatus: {
    readonly New: "new";
    readonly Pause: "pause";
    readonly Active: "active";
    readonly Rejected: "rejected";
    readonly Moderated: "moderated";
    readonly Completed: "completed";
};
export type CampaignStatus = (typeof CampaignStatus)[keyof typeof CampaignStatus];
