/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { UserUsernameAvatar } from './user-username-avatar';
/**
 *
 * @export
 * @interface CommentSchemaWithAuthor
 */
export interface CommentSchemaWithAuthor {
    /**
     *
     * @type {number}
     * @memberof CommentSchemaWithAuthor
     */
    'id': number;
    /**
     *
     * @type {number}
     * @memberof CommentSchemaWithAuthor
     */
    'likes_count'?: number;
    /**
     *
     * @type {boolean}
     * @memberof CommentSchemaWithAuthor
     */
    'is_active'?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof CommentSchemaWithAuthor
     */
    'no_reply'?: boolean;
    /**
     *
     * @type {string}
     * @memberof CommentSchemaWithAuthor
     */
    'deleted_at'?: string | null;
    /**
     *
     * @type {string}
     * @memberof CommentSchemaWithAuthor
     */
    'updated_at': string;
    /**
     *
     * @type {string}
     * @memberof CommentSchemaWithAuthor
     */
    'created_at': string;
    /**
     *
     * @type {string}
     * @memberof CommentSchemaWithAuthor
     */
    'text'?: string | null;
    /**
     *
     * @type {UserUsernameAvatar}
     * @memberof CommentSchemaWithAuthor
     */
    'author': UserUsernameAvatar;
    /**
     *
     * @type {boolean}
     * @memberof CommentSchemaWithAuthor
     */
    'liked'?: boolean;
    /**
     *
     * @type {object}
     * @memberof CommentSchemaWithAuthor
     */
    'reactions'?: object;
}
