/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CommentCreateSchema
 */
export interface CommentCreateSchema {
    /**
     *
     * @type {string}
     * @memberof CommentCreateSchema
     */
    'text': string;
    /**
     *
     * @type {number}
     * @memberof CommentCreateSchema
     */
    'parent_comment_id'?: number;
}
