/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CommentDetailSchema
 */
export interface CommentDetailSchema {
    /**
     *
     * @type {number}
     * @memberof CommentDetailSchema
     */
    id: number;
    /**
     *
     * @type {number}
     * @memberof CommentDetailSchema
     */
    likes_count?: number;
    /**
     *
     * @type {boolean}
     * @memberof CommentDetailSchema
     */
    is_active?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof CommentDetailSchema
     */
    no_reply?: boolean;
    /**
     *
     * @type {string}
     * @memberof CommentDetailSchema
     */
    deleted_at?: string | null;
    /**
     *
     * @type {string}
     * @memberof CommentDetailSchema
     */
    updated_at: string;
    /**
     *
     * @type {string}
     * @memberof CommentDetailSchema
     */
    created_at: string;
    /**
     *
     * @type {string}
     * @memberof CommentDetailSchema
     */
    text?: string | null;
    /**
     *
     * @type {{ [key: string]: number; }}
     * @memberof CommentDetailSchema
     */
    mentioned_users?: {
        [key: string]: number;
    };
}
