/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ReadUrlSchema } from './read-url-schema';
/**
 *
 * @export
 * @interface ContentModelDetailSchema
 */
export interface ContentModelDetailSchema {
    /**
     *
     * @type {number}
     * @memberof ContentModelDetailSchema
     */
    id: number;
    /**
     * PHOTO: photo<br/>VIDEO: video
     * @type {string}
     * @memberof ContentModelDetailSchema
     */
    file_type?: string;
    /**
     * Content-Type header value
     * @type {string}
     * @memberof ContentModelDetailSchema
     */
    content_type?: string;
    /**
     *
     * @type {string}
     * @memberof ContentModelDetailSchema
     */
    hash_name: string;
    /**
     * Number in sequence for object with multiply contents.
     * @type {number}
     * @memberof ContentModelDetailSchema
     */
    number?: number | null;
    /**
     * Thumbnail for videos.
     * @type {string}
     * @memberof ContentModelDetailSchema
     */
    thumbnail_hash_name?: string | null;
    /**
     *
     * @type {Array<any>}
     * @memberof ContentModelDetailSchema
     */
    available_sizes?: Array<any> | null;
    /**
     *
     * @type {Array<any>}
     * @memberof ContentModelDetailSchema
     */
    thumbnail_available_sizes?: Array<any> | null;
    /**
     *
     * @type {any}
     * @memberof ContentModelDetailSchema
     */
    configuration?: any;
    /**
     *
     * @type {Array<ReadUrlSchema>}
     * @memberof ContentModelDetailSchema
     */
    read_urls?: Array<ReadUrlSchema>;
    /**
     *
     * @type {Array<ReadUrlSchema>}
     * @memberof ContentModelDetailSchema
     */
    thumbnail_read_urls?: Array<ReadUrlSchema>;
    /**
     *
     * @type {string}
     * @memberof ContentModelDetailSchema
     */
    gradient_read_url?: string;
}
