/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Firebase tokens to send push-notification.
 * @export
 * @interface FirebaseTokenModelSchema
 */
export interface FirebaseTokenModelSchema {
    /**
     *
     * @type {number}
     * @memberof FirebaseTokenModelSchema
     */
    id: number;
    /**
     * Firebase токен
     * @type {string}
     * @memberof FirebaseTokenModelSchema
     */
    token: string;
    /**
     * Платформа для которой сгенерирован токен
     * @type {string}
     * @memberof FirebaseTokenModelSchema
     */
    platform: string;
    /**
     * Активный токен
     * @type {boolean}
     * @memberof FirebaseTokenModelSchema
     */
    is_active?: boolean;
}
