/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface HashtagSearchSchema
 */
export interface HashtagSearchSchema {
    /**
     *
     * @type {number}
     * @memberof HashtagSearchSchema
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof HashtagSearchSchema
     */
    name: string;
    /**
     *
     * @type {number}
     * @memberof HashtagSearchSchema
     */
    followers_count: number;
    /**
     *
     * @type {number}
     * @memberof HashtagSearchSchema
     */
    score: number;
}
