/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface LocationModelSchema
 */
export interface LocationModelSchema {
    /**
     *
     * @type {number}
     * @memberof LocationModelSchema
     */
    id: number;
    /**
     * Долгота
     * @type {number}
     * @memberof LocationModelSchema
     */
    longitude: number;
    /**
     * Широта
     * @type {number}
     * @memberof LocationModelSchema
     */
    latitude: number;
    /**
     * Адрес
     * @type {string}
     * @memberof LocationModelSchema
     */
    address: string;
    /**
     * Название локации
     * @type {string}
     * @memberof LocationModelSchema
     */
    name?: string | null;
}
