/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { SizeType } from './size-type';
/**
 *
 * @export
 * @interface ReadUrlWithSize
 */
export interface ReadUrlWithSize {
    /**
     *
     * @type {string}
     * @memberof ReadUrlWithSize
     */
    url: string;
    /**
     *
     * @type {number}
     * @memberof ReadUrlWithSize
     */
    width?: number;
    /**
     *
     * @type {number}
     * @memberof ReadUrlWithSize
     */
    height?: number;
    /**
     *
     * @type {SizeType}
     * @memberof ReadUrlWithSize
     */
    size_type: SizeType;
}
