/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { OpenHiddenLists } from './open-hidden-lists';
import type { ReplyPermissionChoices } from './reply-permission-choices';
/**
 *
 * @export
 * @interface StoryUpdateSchema
 */
export interface StoryUpdateSchema {
    /**
     * Списки ID пользователей для которых нужно открыть/закрыть историю
     * @type {OpenHiddenLists}
     * @memberof StoryUpdateSchema
     */
    hide_lists?: OpenHiddenLists;
    /**
     * Кто может отвечать на историю
     * @type {ReplyPermissionChoices}
     * @memberof StoryUpdateSchema
     */
    reply_permission?: ReplyPermissionChoices;
    /**
     * Настройки
     * @type {object}
     * @memberof StoryUpdateSchema
     */
    configuration?: object;
}
