/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface TopicActSchema
 */
export interface TopicActSchema {
    /**
     *
     * @type {string}
     * @memberof TopicActSchema
     */
    account_uuid: string;
    /**
     *
     * @type {string}
     * @memberof TopicActSchema
     */
    topic: string;
}
