/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ContentCreateSchemaWithoutThumbnail } from './content-create-schema-without-thumbnail';
/**
 *
 * @export
 * @interface UpdateCurrentUser
 */
export interface UpdateCurrentUser {
    /**
     *
     * @type {string}
     * @memberof UpdateCurrentUser
     */
    bio?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateCurrentUser
     */
    sex?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateCurrentUser
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateCurrentUser
     */
    link?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateCurrentUser
     */
    username?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateCurrentUser
     */
    birthday?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateCurrentUser
     */
    profession?: string;
    /**
     *
     * @type {ContentCreateSchemaWithoutThumbnail}
     * @memberof UpdateCurrentUser
     */
    content?: ContentCreateSchemaWithoutThumbnail;
    /**
     *
     * @type {boolean}
     * @memberof UpdateCurrentUser
     */
    is_private?: boolean;
}
