/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ContentModelDetailWithoutThumbnail } from './content-model-detail-without-thumbnail';
/**
 *
 * @export
 * @interface UserUsernameAvatar
 */
export interface UserUsernameAvatar {
    /**
     *
     * @type {number}
     * @memberof UserUsernameAvatar
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof UserUsernameAvatar
     */
    username: string;
    /**
     * Uuid of user in auth service.
     * @type {string}
     * @memberof UserUsernameAvatar
     */
    account_id?: string | null;
    /**
     *
     * @type {ContentModelDetailWithoutThumbnail}
     * @memberof UserUsernameAvatar
     */
    profile_photo?: ContentModelDetailWithoutThumbnail;
}
