/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ReadUrlSchema } from './read-url-schema';
/**
 *
 * @export
 * @interface UserStoryFeed
 */
export interface UserStoryFeed {
    /**
     *
     * @type {number}
     * @memberof UserStoryFeed
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof UserStoryFeed
     */
    username: string;
    /**
     *
     * @type {string}
     * @memberof UserStoryFeed
     */
    profile_photo?: string;
    /**
     * All actual stories was viewed.
     * @type {boolean}
     * @memberof UserStoryFeed
     */
    viewed?: boolean;
    /**
     *
     * @type {string}
     * @memberof UserStoryFeed
     */
    last_story_created_at?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof UserStoryFeed
     */
    available_sizes?: Array<string>;
    /**
     *
     * @type {Array<ReadUrlSchema>}
     * @memberof UserStoryFeed
     */
    read_urls?: Array<ReadUrlSchema>;
}
