/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UserGlobalSettings
 */
export interface UserGlobalSettings {
    /**
     *
     * @type {number}
     * @memberof UserGlobalSettings
     */
    'id': number;
    /**
     * Глобальное разрешение на репост актуальных сторис
     * @type {string}
     * @memberof UserGlobalSettings
     */
    'reply_story_permission'?: string;
    /**
     * Auto approve all tags in posts.
     * @type {boolean}
     * @memberof UserGlobalSettings
     */
    'tags_auto_approve'?: boolean;
    /**
     * Push notifications enabled.
     * @type {boolean}
     * @memberof UserGlobalSettings
     */
    'push_notifications_enable'?: boolean;
    /**
     * Visibility of likes
     * @type {boolean}
     * @memberof UserGlobalSettings
     */
    'likes_visible'?: boolean;
    /**
     * Share switch
     * @type {boolean}
     * @memberof UserGlobalSettings
     */
    'share_enabled'?: boolean;
    /**
     * Comments switch
     * @type {boolean}
     * @memberof UserGlobalSettings
     */
    'comments_enabled'?: boolean;
    /**
     * Reactions switch
     * @type {boolean}
     * @memberof UserGlobalSettings
     */
    'reactions_enabled'?: boolean;
}
