/**
 * Yuco Notifications
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AxiosConfiguration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import { type RequestArgs, BaseAPI } from '../base';
import type { UnreadNotification } from '../model';
/**
 * DefaultApi - axios parameter creator
 * @export
 */
export declare const DefaultApiAxiosParamCreator: (configuration?: AxiosConfiguration) => {
    /**
     *
     * @summary Get Notification Feed
     * @param {number} limit
     * @param {string} filter
     * @param {string} [offset]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getNotificationFeedV1NotificationFeedGet: (limit: number, filter: string, offset?: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Get Unread Notifications Flag
     * @param {number} userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getUnreadNotificationsFlagV1UnreadNotificationsUserIdGet: (userId: number, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Read Notifications
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    readNotificationsV1ReadNotificationsPost: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * DefaultApi - functional programming interface
 * @export
 */
export declare const DefaultApiFp: (configuration?: AxiosConfiguration) => {
    /**
     *
     * @summary Get Notification Feed
     * @param {number} limit
     * @param {string} filter
     * @param {string} [offset]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getNotificationFeedV1NotificationFeedGet(limit: number, filter: string, offset?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>>;
    /**
     *
     * @summary Get Unread Notifications Flag
     * @param {number} userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getUnreadNotificationsFlagV1UnreadNotificationsUserIdGet(userId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UnreadNotification>>;
    /**
     *
     * @summary Read Notifications
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    readNotificationsV1ReadNotificationsPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>>;
};
/**
 * Request parameters for getNotificationFeedV1NotificationFeedGet operation in DefaultApi.
 * @export
 * @interface DefaultApiGetNotificationFeedV1NotificationFeedGetRequest
 */
export interface DefaultApiGetNotificationFeedV1NotificationFeedGetRequest {
    /**
     *
     * @type {number}
     * @memberof DefaultApiGetNotificationFeedV1NotificationFeedGet
     */
    readonly limit: number;
    /**
     *
     * @type {string}
     * @memberof DefaultApiGetNotificationFeedV1NotificationFeedGet
     */
    readonly filter: string;
    /**
     *
     * @type {string}
     * @memberof DefaultApiGetNotificationFeedV1NotificationFeedGet
     */
    readonly offset?: string;
}
/**
 * Request parameters for getUnreadNotificationsFlagV1UnreadNotificationsUserIdGet operation in DefaultApi.
 * @export
 * @interface DefaultApiGetUnreadNotificationsFlagV1UnreadNotificationsUserIdGetRequest
 */
export interface DefaultApiGetUnreadNotificationsFlagV1UnreadNotificationsUserIdGetRequest {
    /**
     *
     * @type {number}
     * @memberof DefaultApiGetUnreadNotificationsFlagV1UnreadNotificationsUserIdGet
     */
    readonly userId: number;
}
/**
 * DefaultApi - interface
 * @export
 * @interface DefaultApi
 */
export interface DefaultApiInterface {
    /**
     *
     * @summary Get Notification Feed
     * @param {number} limit
     * @param {string} filter
     * @param {string} [offset]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getNotificationFeedV1NotificationFeedGet(requestParameters: DefaultApiGetNotificationFeedV1NotificationFeedGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<any>;
    /**
     *
     * @summary Get Unread Notifications Flag
     * @param {number} userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getUnreadNotificationsFlagV1UnreadNotificationsUserIdGet(requestParameters: DefaultApiGetUnreadNotificationsFlagV1UnreadNotificationsUserIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<UnreadNotification>;
    /**
     *
     * @summary Read Notifications
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    readNotificationsV1ReadNotificationsPost(options?: RawAxiosRequestConfig): AxiosPromise<any>;
}
/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export declare class DefaultApi extends BaseAPI implements DefaultApiInterface {
    /**
     *
     * @summary Get Notification Feed
     * @param {DefaultApiGetNotificationFeedV1NotificationFeedGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getNotificationFeedV1NotificationFeedGet(requestParameters: DefaultApiGetNotificationFeedV1NotificationFeedGetRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<any, any>>;
    /**
     *
     * @summary Get Unread Notifications Flag
     * @param {DefaultApiGetUnreadNotificationsFlagV1UnreadNotificationsUserIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getUnreadNotificationsFlagV1UnreadNotificationsUserIdGet(requestParameters: DefaultApiGetUnreadNotificationsFlagV1UnreadNotificationsUserIdGetRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<UnreadNotification, any>>;
    /**
     *
     * @summary Read Notifications
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    readNotificationsV1ReadNotificationsPost(options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<any, any>>;
}
