/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AxiosConfiguration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import { type RequestArgs, BaseAPI } from '../base';
import type { AdTemplateCreateSchema } from '../model';
import type { AdTemplateDetailSchema } from '../model';
import type { AdTemplateListSchema } from '../model';
import type { AdTemplateUpdateSchema } from '../model';
/**
 * AdTemplatesApi - axios parameter creator
 * @export
 */
export declare const AdTemplatesApiAxiosParamCreator: (configuration?: AxiosConfiguration) => {
    /**
     *
     * @summary Create Ad Template View
     * @param {AdTemplateCreateSchema} adTemplateCreateSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createAdTemplateViewPost: (adTemplateCreateSchema: AdTemplateCreateSchema, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Delete Ad Template View
     * @param {number} templateId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteAdTemplateViewDelete: (templateId: number, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * ## Available fields for *sort* and *offset*:  - id: int
     * @summary Get Ad Templates View
     * @param {string} [sort] Fields for ordering without spaces and separated by commas.Can be used for ASC and DESC (\&#39;-\&#39; added to the beggining of the field).Example: &amp;sort&#x3D;-username,created_at
     * @param {string} [offset] Values of last received row which used in sort. Example with sort: sort&#x3D;username,-id&amp;offset&#x3D;username123,987
     * @param {number} [limit] Limit of rows count in the response
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAdTemplatesViewGet: (sort?: string, offset?: string, limit?: number, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Update Ad Template View
     * @param {number} templateId
     * @param {AdTemplateUpdateSchema} adTemplateUpdateSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateAdTemplateViewPatch: (templateId: number, adTemplateUpdateSchema: AdTemplateUpdateSchema, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * AdTemplatesApi - functional programming interface
 * @export
 */
export declare const AdTemplatesApiFp: (configuration?: AxiosConfiguration) => {
    /**
     *
     * @summary Create Ad Template View
     * @param {AdTemplateCreateSchema} adTemplateCreateSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createAdTemplateViewPost(adTemplateCreateSchema: AdTemplateCreateSchema, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdTemplateDetailSchema>>;
    /**
     *
     * @summary Delete Ad Template View
     * @param {number} templateId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteAdTemplateViewDelete(templateId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>>;
    /**
     * ## Available fields for *sort* and *offset*:  - id: int
     * @summary Get Ad Templates View
     * @param {string} [sort] Fields for ordering without spaces and separated by commas.Can be used for ASC and DESC (\&#39;-\&#39; added to the beggining of the field).Example: &amp;sort&#x3D;-username,created_at
     * @param {string} [offset] Values of last received row which used in sort. Example with sort: sort&#x3D;username,-id&amp;offset&#x3D;username123,987
     * @param {number} [limit] Limit of rows count in the response
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAdTemplatesViewGet(sort?: string, offset?: string, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdTemplateListSchema>>;
    /**
     *
     * @summary Update Ad Template View
     * @param {number} templateId
     * @param {AdTemplateUpdateSchema} adTemplateUpdateSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateAdTemplateViewPatch(templateId: number, adTemplateUpdateSchema: AdTemplateUpdateSchema, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>>;
};
/**
 * Request parameters for createAdTemplateViewPost operation in AdTemplatesApi.
 * @export
 * @interface AdTemplatesApiCreateAdTemplateViewPostRequest
 */
export interface AdTemplatesApiCreateAdTemplateViewPostRequest {
    /**
     *
     * @type {AdTemplateCreateSchema}
     * @memberof AdTemplatesApiCreateAdTemplateViewPost
     */
    readonly adTemplateCreateSchema: AdTemplateCreateSchema;
}
/**
 * Request parameters for deleteAdTemplateViewDelete operation in AdTemplatesApi.
 * @export
 * @interface AdTemplatesApiDeleteAdTemplateViewDeleteRequest
 */
export interface AdTemplatesApiDeleteAdTemplateViewDeleteRequest {
    /**
     *
     * @type {number}
     * @memberof AdTemplatesApiDeleteAdTemplateViewDelete
     */
    readonly templateId: number;
}
/**
 * Request parameters for getAdTemplatesViewGet operation in AdTemplatesApi.
 * @export
 * @interface AdTemplatesApiGetAdTemplatesViewGetRequest
 */
export interface AdTemplatesApiGetAdTemplatesViewGetRequest {
    /**
     * Fields for ordering without spaces and separated by commas.Can be used for ASC and DESC (\&#39;-\&#39; added to the beggining of the field).Example: &amp;sort&#x3D;-username,created_at
     * @type {string}
     * @memberof AdTemplatesApiGetAdTemplatesViewGet
     */
    readonly sort?: string;
    /**
     * Values of last received row which used in sort. Example with sort: sort&#x3D;username,-id&amp;offset&#x3D;username123,987
     * @type {string}
     * @memberof AdTemplatesApiGetAdTemplatesViewGet
     */
    readonly offset?: string;
    /**
     * Limit of rows count in the response
     * @type {number}
     * @memberof AdTemplatesApiGetAdTemplatesViewGet
     */
    readonly limit?: number;
}
/**
 * Request parameters for updateAdTemplateViewPatch operation in AdTemplatesApi.
 * @export
 * @interface AdTemplatesApiUpdateAdTemplateViewPatchRequest
 */
export interface AdTemplatesApiUpdateAdTemplateViewPatchRequest {
    /**
     *
     * @type {number}
     * @memberof AdTemplatesApiUpdateAdTemplateViewPatch
     */
    readonly templateId: number;
    /**
     *
     * @type {AdTemplateUpdateSchema}
     * @memberof AdTemplatesApiUpdateAdTemplateViewPatch
     */
    readonly adTemplateUpdateSchema: AdTemplateUpdateSchema;
}
/**
 * AdTemplatesApi - interface
 * @export
 * @interface AdTemplatesApi
 */
export interface AdTemplatesApiInterface {
    /**
     *
     * @summary Create Ad Template View
     * @param {AdTemplateCreateSchema} adTemplateCreateSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdTemplatesApiInterface
     */
    createAdTemplateViewPost(requestParameters: AdTemplatesApiCreateAdTemplateViewPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<AdTemplateDetailSchema>;
    /**
     *
     * @summary Delete Ad Template View
     * @param {number} templateId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdTemplatesApiInterface
     */
    deleteAdTemplateViewDelete(requestParameters: AdTemplatesApiDeleteAdTemplateViewDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<any>;
    /**
     * ## Available fields for *sort* and *offset*:  - id: int
     * @summary Get Ad Templates View
     * @param {string} [sort] Fields for ordering without spaces and separated by commas.Can be used for ASC and DESC (\&#39;-\&#39; added to the beggining of the field).Example: &amp;sort&#x3D;-username,created_at
     * @param {string} [offset] Values of last received row which used in sort. Example with sort: sort&#x3D;username,-id&amp;offset&#x3D;username123,987
     * @param {number} [limit] Limit of rows count in the response
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdTemplatesApiInterface
     */
    getAdTemplatesViewGet(requestParameters: AdTemplatesApiGetAdTemplatesViewGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<AdTemplateListSchema>;
    /**
     *
     * @summary Update Ad Template View
     * @param {number} templateId
     * @param {AdTemplateUpdateSchema} adTemplateUpdateSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdTemplatesApiInterface
     */
    updateAdTemplateViewPatch(requestParameters: AdTemplatesApiUpdateAdTemplateViewPatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<any>;
}
/**
 * AdTemplatesApi - object-oriented interface
 * @export
 * @class AdTemplatesApi
 * @extends {BaseAPI}
 */
export declare class AdTemplatesApi extends BaseAPI implements AdTemplatesApiInterface {
    /**
     *
     * @summary Create Ad Template View
     * @param {AdTemplatesApiCreateAdTemplateViewPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdTemplatesApi
     */
    createAdTemplateViewPost(requestParameters: AdTemplatesApiCreateAdTemplateViewPostRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<AdTemplateDetailSchema, any>>;
    /**
     *
     * @summary Delete Ad Template View
     * @param {AdTemplatesApiDeleteAdTemplateViewDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdTemplatesApi
     */
    deleteAdTemplateViewDelete(requestParameters: AdTemplatesApiDeleteAdTemplateViewDeleteRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<any, any>>;
    /**
     * ## Available fields for *sort* and *offset*:  - id: int
     * @summary Get Ad Templates View
     * @param {AdTemplatesApiGetAdTemplatesViewGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdTemplatesApi
     */
    getAdTemplatesViewGet(requestParameters?: AdTemplatesApiGetAdTemplatesViewGetRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<AdTemplateListSchema, any>>;
    /**
     *
     * @summary Update Ad Template View
     * @param {AdTemplatesApiUpdateAdTemplateViewPatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdTemplatesApi
     */
    updateAdTemplateViewPatch(requestParameters: AdTemplatesApiUpdateAdTemplateViewPatchRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<any, any>>;
}
