/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AxiosConfiguration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import { type RequestArgs, BaseAPI } from '../base';
import type { CurrencyList } from '../model';
/**
 * CurrenciesApi - axios parameter creator
 * @export
 */
export declare const CurrenciesApiAxiosParamCreator: (configuration?: AxiosConfiguration) => {
    /**
     * ## Available fields for *sort* and *offset*:  - id: int - abbr: str - name: str
     * @summary List Timezones View
     * @param {string} [sort] Fields for ordering without spaces and separated by commas.Can be used for ASC and DESC (\&#39;-\&#39; added to the beggining of the field).Example: &amp;sort&#x3D;-username,created_at
     * @param {string} [offset] Values of last received row which used in sort. Example with sort: sort&#x3D;username,-id&amp;offset&#x3D;username123,987
     * @param {number} [limit] Limit of rows count in the response
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listTimezonesViewGet: (sort?: string, offset?: string, limit?: number, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * CurrenciesApi - functional programming interface
 * @export
 */
export declare const CurrenciesApiFp: (configuration?: AxiosConfiguration) => {
    /**
     * ## Available fields for *sort* and *offset*:  - id: int - abbr: str - name: str
     * @summary List Timezones View
     * @param {string} [sort] Fields for ordering without spaces and separated by commas.Can be used for ASC and DESC (\&#39;-\&#39; added to the beggining of the field).Example: &amp;sort&#x3D;-username,created_at
     * @param {string} [offset] Values of last received row which used in sort. Example with sort: sort&#x3D;username,-id&amp;offset&#x3D;username123,987
     * @param {number} [limit] Limit of rows count in the response
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listTimezonesViewGet(sort?: string, offset?: string, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CurrencyList>>;
};
/**
 * Request parameters for listTimezonesViewGet operation in CurrenciesApi.
 * @export
 * @interface CurrenciesApiListTimezonesViewGetRequest
 */
export interface CurrenciesApiListTimezonesViewGetRequest {
    /**
     * Fields for ordering without spaces and separated by commas.Can be used for ASC and DESC (\&#39;-\&#39; added to the beggining of the field).Example: &amp;sort&#x3D;-username,created_at
     * @type {string}
     * @memberof CurrenciesApiListTimezonesViewGet
     */
    readonly sort?: string;
    /**
     * Values of last received row which used in sort. Example with sort: sort&#x3D;username,-id&amp;offset&#x3D;username123,987
     * @type {string}
     * @memberof CurrenciesApiListTimezonesViewGet
     */
    readonly offset?: string;
    /**
     * Limit of rows count in the response
     * @type {number}
     * @memberof CurrenciesApiListTimezonesViewGet
     */
    readonly limit?: number;
}
/**
 * CurrenciesApi - interface
 * @export
 * @interface CurrenciesApi
 */
export interface CurrenciesApiInterface {
    /**
     * ## Available fields for *sort* and *offset*:  - id: int - abbr: str - name: str
     * @summary List Timezones View
     * @param {string} [sort] Fields for ordering without spaces and separated by commas.Can be used for ASC and DESC (\&#39;-\&#39; added to the beggining of the field).Example: &amp;sort&#x3D;-username,created_at
     * @param {string} [offset] Values of last received row which used in sort. Example with sort: sort&#x3D;username,-id&amp;offset&#x3D;username123,987
     * @param {number} [limit] Limit of rows count in the response
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CurrenciesApiInterface
     */
    listTimezonesViewGet(requestParameters: CurrenciesApiListTimezonesViewGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<CurrencyList>;
}
/**
 * CurrenciesApi - object-oriented interface
 * @export
 * @class CurrenciesApi
 * @extends {BaseAPI}
 */
export declare class CurrenciesApi extends BaseAPI implements CurrenciesApiInterface {
    /**
     * ## Available fields for *sort* and *offset*:  - id: int - abbr: str - name: str
     * @summary List Timezones View
     * @param {CurrenciesApiListTimezonesViewGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CurrenciesApi
     */
    listTimezonesViewGet(requestParameters?: CurrenciesApiListTimezonesViewGetRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<CurrencyList, any>>;
}
