/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AxiosInstance } from 'axios';
import { AdTemplatesApiInterface } from './api/ad-templates-api';
import { AdsApiInterface } from './api/ads-api';
import { AdvertisementCampaignsApiInterface } from './api/advertisement-campaigns-api';
import { AdvertisementGroupsApiInterface } from './api/advertisement-groups-api';
import { AdvertisementProfilesApiInterface } from './api/advertisement-profiles-api';
import { AudienceApiInterface } from './api/audience-api';
import { CommentsApiInterface } from './api/comments-api';
import { CountriesApiInterface } from './api/countries-api';
import { CurrenciesApiInterface } from './api/currencies-api';
import { DefaultApiInterface } from './api/default-api';
import { FollowApiInterface } from './api/follow-api';
import { HashtagApiInterface } from './api/hashtag-api';
import { IOFilesApiInterface } from './api/iofiles-api';
import { LocationsApiInterface } from './api/locations-api';
import { NotificatonsApiInterface } from './api/notificatons-api';
import { PhoneCodesApiInterface } from './api/phone-codes-api';
import { PostApiInterface } from './api/post-api';
import { PrivateApiInterface } from './api/private-api';
import { PublicDocumentApiInterface } from './api/public-document-api';
import { ReactionApiInterface } from './api/reaction-api';
import { StoryApiInterface } from './api/story-api';
import { TimezonesApiInterface } from './api/timezones-api';
import { UserApiInterface } from './api/user-api';
import { ViewsApiInterface } from './api/views-api';
export interface YucoBackendApiGetterInterface {
    getAdTemplatesApi: () => AdTemplatesApiInterface;
    getAdsApi: () => AdsApiInterface;
    getAdvertisementCampaignsApi: () => AdvertisementCampaignsApiInterface;
    getAdvertisementGroupsApi: () => AdvertisementGroupsApiInterface;
    getAdvertisementProfilesApi: () => AdvertisementProfilesApiInterface;
    getAudienceApi: () => AudienceApiInterface;
    getCommentsApi: () => CommentsApiInterface;
    getCountriesApi: () => CountriesApiInterface;
    getCurrenciesApi: () => CurrenciesApiInterface;
    getDefaultApi: () => DefaultApiInterface;
    getFollowApi: () => FollowApiInterface;
    getHashtagApi: () => HashtagApiInterface;
    getIOFilesApi: () => IOFilesApiInterface;
    getLocationsApi: () => LocationsApiInterface;
    getNotificatonsApi: () => NotificatonsApiInterface;
    getPhoneCodesApi: () => PhoneCodesApiInterface;
    getPostApi: () => PostApiInterface;
    getPrivateApi: () => PrivateApiInterface;
    getPublicDocumentApi: () => PublicDocumentApiInterface;
    getReactionApi: () => ReactionApiInterface;
    getStoryApi: () => StoryApiInterface;
    getTimezonesApi: () => TimezonesApiInterface;
    getUserApi: () => UserApiInterface;
    getViewsApi: () => ViewsApiInterface;
}
export declare const yucoBackendConfigureGetter: (applyInterceptors: <T>(apiCreator: (axios: AxiosInstance) => T) => T) => YucoBackendApiGetterInterface;
