/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { PostDetailSchema } from './post-detail-schema';
import type { StoryModelSchemaDetail } from './story-model-schema-detail';
/**
 *
 * @export
 * @interface AdExtendedDetailSchema
 */
export interface AdExtendedDetailSchema {
    /**
     *
     * @type {string}
     * @memberof AdExtendedDetailSchema
     */
    start_date: string;
    /**
     * STORY: story<br/>POST: post
     * @type {string}
     * @memberof AdExtendedDetailSchema
     */
    variation: string;
    /**
     *
     * @type {PostDetailSchema}
     * @memberof AdExtendedDetailSchema
     */
    post?: PostDetailSchema;
    /**
     *
     * @type {StoryModelSchemaDetail}
     * @memberof AdExtendedDetailSchema
     */
    story?: StoryModelSchemaDetail;
    /**
     *
     * @type {number}
     * @memberof AdExtendedDetailSchema
     */
    likes: number;
    /**
     *
     * @type {number}
     * @memberof AdExtendedDetailSchema
     */
    activity: number;
    /**
     *
     * @type {number}
     * @memberof AdExtendedDetailSchema
     */
    saves?: number;
    /**
     *
     * @type {number}
     * @memberof AdExtendedDetailSchema
     */
    shares?: number;
}
