/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AdvertisingObject } from './advertising-object';
import type { CampaignGoal } from './campaign-goal';
/**
 *
 * @export
 * @interface AdvertisementCampaignUpdateSchema
 */
export interface AdvertisementCampaignUpdateSchema {
    /**
     *
     * @type {string}
     * @memberof AdvertisementCampaignUpdateSchema
     */
    name?: string;
    /**
     *
     * @type {AdvertisingObject}
     * @memberof AdvertisementCampaignUpdateSchema
     */
    advertising_obj?: AdvertisingObject;
    /**
     *
     * @type {CampaignGoal}
     * @memberof AdvertisementCampaignUpdateSchema
     */
    goal?: CampaignGoal;
    /**
     *
     * @type {number}
     * @memberof AdvertisementCampaignUpdateSchema
     */
    budget?: number;
    /**
     *
     * @type {string}
     * @memberof AdvertisementCampaignUpdateSchema
     */
    period_start?: string;
    /**
     *
     * @type {string}
     * @memberof AdvertisementCampaignUpdateSchema
     */
    period_end?: string;
    /**
     * campaign url (website, mobile app, profile, etc)
     * @type {string}
     * @memberof AdvertisementCampaignUpdateSchema
     */
    link?: string;
}
