/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface AdvertisementCampaignDetailSchema
 */
export interface AdvertisementCampaignDetailSchema {
    /**
     *
     * @type {number}
     * @memberof AdvertisementCampaignDetailSchema
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof AdvertisementCampaignDetailSchema
     */
    name: string;
    /**
     * ACCOUNT: ACCOUNT<br/>WEB_SITE: web_site<br/>MOBILE_APP: mobile_app<br/>SERVICES_AND_GOODS: services_and_goods
     * @type {string}
     * @memberof AdvertisementCampaignDetailSchema
     */
    advertising_obj: string;
    /**
     * campaign url
     * @type {string}
     * @memberof AdvertisementCampaignDetailSchema
     */
    link: string;
    /**
     * LEAD_GENERATION: lead_generation<br/>INCREASE_INSTALLS: increase_installs
     * @type {string}
     * @memberof AdvertisementCampaignDetailSchema
     */
    goal: string;
    /**
     *
     * @type {number}
     * @memberof AdvertisementCampaignDetailSchema
     */
    budget: number;
    /**
     * NEW: new<br/>PAUSE: pause<br/>ACTIVE: active<br/>REJECTED: rejected<br/>MODERATED: moderated<br/>COMPLETED: completed
     * @type {string}
     * @memberof AdvertisementCampaignDetailSchema
     */
    status: string;
    /**
     *
     * @type {boolean}
     * @memberof AdvertisementCampaignDetailSchema
     */
    is_archived?: boolean;
    /**
     *
     * @type {string}
     * @memberof AdvertisementCampaignDetailSchema
     */
    created_at: string;
    /**
     *
     * @type {string}
     * @memberof AdvertisementCampaignDetailSchema
     */
    period_start: string;
    /**
     *
     * @type {string}
     * @memberof AdvertisementCampaignDetailSchema
     */
    period_end: string;
    /**
     *
     * @type {number}
     * @memberof AdvertisementCampaignDetailSchema
     */
    groups_budget_total?: number;
    /**
     *
     * @type {number}
     * @memberof AdvertisementCampaignDetailSchema
     */
    budget_constraint?: number;
}
