/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { GroupPosition } from './group-position';
import type { PriceType } from './price-type';
/**
 *
 * @export
 * @interface AdvertisementGroupUpdateSchema
 */
export interface AdvertisementGroupUpdateSchema {
    /**
     *
     * @type {number}
     * @memberof AdvertisementGroupUpdateSchema
     */
    'campaign_id'?: number;
    /**
     *
     * @type {number}
     * @memberof AdvertisementGroupUpdateSchema
     */
    'audience_id'?: number;
    /**
     *
     * @type {string}
     * @memberof AdvertisementGroupUpdateSchema
     */
    'name'?: string;
    /**
     *
     * @type {GroupPosition}
     * @memberof AdvertisementGroupUpdateSchema
     */
    'position'?: GroupPosition;
    /**
     *
     * @type {PriceType}
     * @memberof AdvertisementGroupUpdateSchema
     */
    'price_type'?: PriceType;
    /**
     *
     * @type {number}
     * @memberof AdvertisementGroupUpdateSchema
     */
    'price'?: number;
    /**
     *
     * @type {number}
     * @memberof AdvertisementGroupUpdateSchema
     */
    'budget_constraint'?: number;
    /**
     *
     * @type {string}
     * @memberof AdvertisementGroupUpdateSchema
     */
    'run_time_start'?: string;
    /**
     *
     * @type {string}
     * @memberof AdvertisementGroupUpdateSchema
     */
    'run_time_end'?: string;
}
