/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface AdvertisementGroup
 */
export interface AdvertisementGroup {
    /**
     *
     * @type {number}
     * @memberof AdvertisementGroup
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof AdvertisementGroup
     */
    name: string;
    /**
     * IN_THE_FEED: in_the_feed<br/>IN_STORIES: in_stories<br/>IN_SEARCH: in_search
     * @type {string}
     * @memberof AdvertisementGroup
     */
    position: string;
    /**
     * CPC: cpc<br/>CPM: cpm
     * @type {string}
     * @memberof AdvertisementGroup
     */
    price_type: string;
    /**
     *
     * @type {number}
     * @memberof AdvertisementGroup
     */
    price: number;
    /**
     *
     * @type {number}
     * @memberof AdvertisementGroup
     */
    budget_constraint: number;
    /**
     * NEW: new<br/>PAUSE: pause<br/>ACTIVE: active<br/>REJECTED: rejected<br/>MODERATED: moderated<br/>COMPLETED: completed
     * @type {string}
     * @memberof AdvertisementGroup
     */
    status: string;
    /**
     *
     * @type {string}
     * @memberof AdvertisementGroup
     */
    run_time_start: string;
    /**
     *
     * @type {string}
     * @memberof AdvertisementGroup
     */
    run_time_end: string;
}
