/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AdvertisementCampaign } from './advertisement-campaign';
import type { Audience } from './audience';
/**
 *
 * @export
 * @interface AdvertisementGroupDetailSchema
 */
export interface AdvertisementGroupDetailSchema {
    /**
     *
     * @type {number}
     * @memberof AdvertisementGroupDetailSchema
     */
    'id': number;
    /**
     *
     * @type {string}
     * @memberof AdvertisementGroupDetailSchema
     */
    'name': string;
    /**
     * IN_THE_FEED: in_the_feed<br/>IN_STORIES: in_stories<br/>IN_SEARCH: in_search
     * @type {string}
     * @memberof AdvertisementGroupDetailSchema
     */
    'position': string;
    /**
     * CPC: cpc<br/>CPM: cpm
     * @type {string}
     * @memberof AdvertisementGroupDetailSchema
     */
    'price_type': string;
    /**
     *
     * @type {number}
     * @memberof AdvertisementGroupDetailSchema
     */
    'price': number;
    /**
     *
     * @type {number}
     * @memberof AdvertisementGroupDetailSchema
     */
    'budget_constraint': number;
    /**
     * NEW: new<br/>PAUSE: pause<br/>ACTIVE: active<br/>REJECTED: rejected<br/>MODERATED: moderated<br/>COMPLETED: completed
     * @type {string}
     * @memberof AdvertisementGroupDetailSchema
     */
    'status': string;
    /**
     *
     * @type {string}
     * @memberof AdvertisementGroupDetailSchema
     */
    'run_time_start': string;
    /**
     *
     * @type {string}
     * @memberof AdvertisementGroupDetailSchema
     */
    'run_time_end': string;
    /**
     *
     * @type {AdvertisementCampaign}
     * @memberof AdvertisementGroupDetailSchema
     */
    'advertisement_campaign': AdvertisementCampaign;
    /**
     *
     * @type {Audience}
     * @memberof AdvertisementGroupDetailSchema
     */
    'audience': Audience;
}
