/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AdvertisingObject } from './advertising-object';
import type { CampaignGoal } from './campaign-goal';
/**
 *
 * @export
 * @interface AdvertisementCampaignCreateSchema
 */
export interface AdvertisementCampaignCreateSchema {
    /**
     *
     * @type {string}
     * @memberof AdvertisementCampaignCreateSchema
     */
    name: string;
    /**
     *
     * @type {AdvertisingObject}
     * @memberof AdvertisementCampaignCreateSchema
     */
    advertising_obj: AdvertisingObject;
    /**
     *
     * @type {CampaignGoal}
     * @memberof AdvertisementCampaignCreateSchema
     */
    goal: CampaignGoal;
    /**
     *
     * @type {number}
     * @memberof AdvertisementCampaignCreateSchema
     */
    budget: number;
    /**
     *
     * @type {string}
     * @memberof AdvertisementCampaignCreateSchema
     */
    period_start: string;
    /**
     *
     * @type {string}
     * @memberof AdvertisementCampaignCreateSchema
     */
    period_end: string;
    /**
     * campaign url (website, mobile app, profile, etc)
     * @type {string}
     * @memberof AdvertisementCampaignCreateSchema
     */
    link: string;
}
