/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CommentSchemaWithAuthor } from './comment-schema-with-author';
/**
 *
 * @export
 * @interface CommentListSchema
 */
export interface CommentListSchema {
    /**
     *
     * @type {Array<CommentSchemaWithAuthor>}
     * @memberof CommentListSchema
     */
    'data': Array<CommentSchemaWithAuthor>;
    /**
     *
     * @type {{ [key: string]: number; }}
     * @memberof CommentListSchema
     */
    'mentioned_users'?: {
        [key: string]: number;
    };
}
