/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { FileTypeChoices } from './file-type-choices';
import type { ReadUrlSchema } from './read-url-schema';
/**
 *
 * @export
 * @interface ContentSchemaWithoutThumbnail
 */
export interface ContentSchemaWithoutThumbnail {
    /**
     *
     * @type {FileTypeChoices}
     * @memberof ContentSchemaWithoutThumbnail
     */
    file_type?: FileTypeChoices;
    /**
     *
     * @type {string}
     * @memberof ContentSchemaWithoutThumbnail
     */
    content_type?: string;
    /**
     *
     * @type {string}
     * @memberof ContentSchemaWithoutThumbnail
     */
    hash_name: string;
    /**
     *
     * @type {Array<string>}
     * @memberof ContentSchemaWithoutThumbnail
     */
    available_sizes: Array<string>;
    /**
     *
     * @type {Array<ReadUrlSchema>}
     * @memberof ContentSchemaWithoutThumbnail
     */
    read_urls?: Array<ReadUrlSchema>;
}
