/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ContentOverlayCandidateSchema } from './content-overlay-candidate-schema';
import type { ScreenResolution } from './screen-resolution';
/**
 *
 * @export
 * @interface ContentOverlaySchema
 */
export interface ContentOverlaySchema {
    /**
     * Список медиа объектов для наложения на видео
     * @type {Array<ContentOverlayCandidateSchema>}
     * @memberof ContentOverlaySchema
     */
    'candidates'?: Array<ContentOverlayCandidateSchema>;
    /**
     * Размер виртуального экрана
     * @type {ScreenResolution}
     * @memberof ContentOverlaySchema
     */
    'screen'?: ScreenResolution;
}
