/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Currency
 */
export interface Currency {
    /**
     *
     * @type {number}
     * @memberof Currency
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof Currency
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof Currency
     */
    abbr: string;
}
