/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Firebase tokens to send push-notification.
 * @export
 * @interface FirebaseHotTokenModelSchema
 */
export interface FirebaseHotTokenModelSchema {
    /**
     * Firebase токен
     * @type {string}
     * @memberof FirebaseHotTokenModelSchema
     */
    token: string;
    /**
     * Платформа для которой сгенерирован токен
     * @type {string}
     * @memberof FirebaseHotTokenModelSchema
     */
    platform: string;
}
