/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface HashtagStatisticSchema
 */
export interface HashtagStatisticSchema {
    /**
     *
     * @type {number}
     * @memberof HashtagStatisticSchema
     */
    posts_count?: number;
    /**
     *
     * @type {number}
     * @memberof HashtagStatisticSchema
     */
    likes_count?: number;
    /**
     *
     * @type {number}
     * @memberof HashtagStatisticSchema
     */
    followers_count?: number;
}
