/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ContentSchemaWithoutThumbnail } from './content-schema-without-thumbnail';
/**
 *
 * @export
 * @interface LocationSchema
 */
export interface LocationSchema {
    /**
     *
     * @type {number}
     * @memberof LocationSchema
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof LocationSchema
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof LocationSchema
     */
    address: string;
    /**
     *
     * @type {number}
     * @memberof LocationSchema
     */
    longitude: number;
    /**
     *
     * @type {number}
     * @memberof LocationSchema
     */
    latitude: number;
    /**
     *
     * @type {ContentSchemaWithoutThumbnail}
     * @memberof LocationSchema
     */
    content?: ContentSchemaWithoutThumbnail;
    /**
     *
     * @type {number}
     * @memberof LocationSchema
     */
    score: number;
}
