/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { LocationSearchSchema } from './location-search-schema';
/**
 *
 * @export
 * @interface LocationsSearchListSchema
 */
export interface LocationsSearchListSchema {
    /**
     *
     * @type {Array<LocationSearchSchema>}
     * @memberof LocationsSearchListSchema
     */
    data: Array<LocationSearchSchema>;
}
