/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ContentModelDetailSchema } from './content-model-detail-schema';
/**
 *
 * @export
 * @interface LocationDetailSchema
 */
export interface LocationDetailSchema {
    /**
     *
     * @type {number}
     * @memberof LocationDetailSchema
     */
    'id': number;
    /**
     * Долгота
     * @type {number}
     * @memberof LocationDetailSchema
     */
    'longitude': number;
    /**
     * Широта
     * @type {number}
     * @memberof LocationDetailSchema
     */
    'latitude': number;
    /**
     * Адрес
     * @type {string}
     * @memberof LocationDetailSchema
     */
    'address': string;
    /**
     * Название локации
     * @type {string}
     * @memberof LocationDetailSchema
     */
    'name'?: string | null;
    /**
     *
     * @type {ContentModelDetailSchema}
     * @memberof LocationDetailSchema
     */
    'content'?: ContentModelDetailSchema;
}
