/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PhoneCodes
 */
export interface PhoneCodes {
    /**
     *
     * @type {number}
     * @memberof PhoneCodes
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof PhoneCodes
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof PhoneCodes
     */
    mask: string;
    /**
     *
     * @type {string}
     * @memberof PhoneCodes
     */
    index: string;
    /**
     *
     * @type {string}
     * @memberof PhoneCodes
     */
    cc: string;
    /**
     *
     * @type {string}
     * @memberof PhoneCodes
     */
    flag?: string | null;
}
