/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AppsPostsShemasPostTagUserSchema } from './apps-posts-shemas-post-tag-user-schema';
import type { ContentCreateSchema } from './content-create-schema';
import type { LocationSearchSchema } from './location-search-schema';
/**
 *
 * @export
 * @interface PostUpdateSchema
 */
export interface PostUpdateSchema {
    /**
     *
     * @type {string}
     * @memberof PostUpdateSchema
     */
    title?: string;
    /**
     *
     * @type {string}
     * @memberof PostUpdateSchema
     */
    tag_color?: string;
    /**
     *
     * @type {boolean}
     * @memberof PostUpdateSchema
     */
    likes_visible?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PostUpdateSchema
     */
    full_size_mode?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PostUpdateSchema
     */
    share_enable?: boolean;
    /**
     * Локация
     * @type {LocationSearchSchema}
     * @memberof PostUpdateSchema
     */
    location?: LocationSearchSchema;
    /**
     * Post contents in the right order.
     * @type {Array<ContentCreateSchema>}
     * @memberof PostUpdateSchema
     */
    contents?: Array<ContentCreateSchema>;
    /**
     * ID отмеченных пользователей
     * @type {Array<AppsPostsShemasPostTagUserSchema>}
     * @memberof PostUpdateSchema
     */
    tag_people?: Array<AppsPostsShemasPostTagUserSchema>;
    /**
     *
     * @type {number}
     * @memberof PostUpdateSchema
     */
    aspect_ratio?: number;
    /**
     *
     * @type {number}
     * @memberof PostUpdateSchema
     */
    height?: number;
    /**
     *
     * @type {boolean}
     * @memberof PostUpdateSchema
     */
    is_draft?: boolean;
    /**
     * Draft settings.
     * @type {object}
     * @memberof PostUpdateSchema
     */
    configuration?: object;
}
