/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ContentTagSchema } from './content-tag-schema';
import type { LocationModelSchema } from './location-model-schema';
/**
 *
 * @export
 * @interface PostDetailSchema
 */
export interface PostDetailSchema {
    /**
     *
     * @type {number}
     * @memberof PostDetailSchema
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof PostDetailSchema
     */
    title?: string | null;
    /**
     *
     * @type {string}
     * @memberof PostDetailSchema
     */
    deleted_at?: string | null;
    /**
     *
     * @type {string}
     * @memberof PostDetailSchema
     */
    updated_at?: string | null;
    /**
     *
     * @type {string}
     * @memberof PostDetailSchema
     */
    created_at: string;
    /**
     * Цвет поста
     * @type {string}
     * @memberof PostDetailSchema
     */
    tag_color: string;
    /**
     *
     * @type {number}
     * @memberof PostDetailSchema
     */
    height?: number | null;
    /**
     *
     * @type {number}
     * @memberof PostDetailSchema
     */
    aspect_ratio?: number | null;
    /**
     *
     * @type {boolean}
     * @memberof PostDetailSchema
     */
    share_to_vk?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PostDetailSchema
     */
    likes_visible?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PostDetailSchema
     */
    share_enable?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PostDetailSchema
     */
    comments_enable?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PostDetailSchema
     */
    reactions_enable?: boolean;
    /**
     *
     * @type {any}
     * @memberof PostDetailSchema
     */
    configuration?: any;
    /**
     *
     * @type {string}
     * @memberof PostDetailSchema
     */
    content_type?: string | null;
    /**
     *
     * @type {number}
     * @memberof PostDetailSchema
     */
    progress_status?: number;
    /**
     *
     * @type {LocationModelSchema}
     * @memberof PostDetailSchema
     */
    location?: LocationModelSchema;
    /**
     *
     * @type {Array<ContentTagSchema>}
     * @memberof PostDetailSchema
     */
    contents: Array<ContentTagSchema>;
    /**
     *
     * @type {{ [key: string]: number; }}
     * @memberof PostDetailSchema
     */
    reactions?: {
        [key: string]: number;
    };
    /**
     *
     * @type {{ [key: string]: number; }}
     * @memberof PostDetailSchema
     */
    mentioned_users?: {
        [key: string]: number;
    };
}
