/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ContentTagSchema } from './content-tag-schema';
import type { LocationModelSchema } from './location-model-schema';
import type { UserModelWithPhoto } from './user-model-with-photo';
/**
 *
 * @export
 * @interface PostDetailSchemaWithFlags
 */
export interface PostDetailSchemaWithFlags {
    /**
     *
     * @type {number}
     * @memberof PostDetailSchemaWithFlags
     */
    'id': number;
    /**
     *
     * @type {string}
     * @memberof PostDetailSchemaWithFlags
     */
    'title'?: string | null;
    /**
     *
     * @type {string}
     * @memberof PostDetailSchemaWithFlags
     */
    'deleted_at'?: string | null;
    /**
     *
     * @type {string}
     * @memberof PostDetailSchemaWithFlags
     */
    'updated_at'?: string | null;
    /**
     *
     * @type {string}
     * @memberof PostDetailSchemaWithFlags
     */
    'created_at': string;
    /**
     * Цвет поста
     * @type {string}
     * @memberof PostDetailSchemaWithFlags
     */
    'tag_color': string;
    /**
     *
     * @type {number}
     * @memberof PostDetailSchemaWithFlags
     */
    'height'?: number | null;
    /**
     *
     * @type {number}
     * @memberof PostDetailSchemaWithFlags
     */
    'aspect_ratio'?: number | null;
    /**
     *
     * @type {boolean}
     * @memberof PostDetailSchemaWithFlags
     */
    'share_to_vk'?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PostDetailSchemaWithFlags
     */
    'likes_visible'?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PostDetailSchemaWithFlags
     */
    'share_enable'?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PostDetailSchemaWithFlags
     */
    'comments_enable'?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PostDetailSchemaWithFlags
     */
    'reactions_enable'?: boolean;
    /**
     *
     * @type {any}
     * @memberof PostDetailSchemaWithFlags
     */
    'configuration'?: any;
    /**
     *
     * @type {string}
     * @memberof PostDetailSchemaWithFlags
     */
    'content_type'?: string | null;
    /**
     *
     * @type {number}
     * @memberof PostDetailSchemaWithFlags
     */
    'progress_status'?: number;
    /**
     *
     * @type {UserModelWithPhoto}
     * @memberof PostDetailSchemaWithFlags
     */
    'author': UserModelWithPhoto;
    /**
     *
     * @type {LocationModelSchema}
     * @memberof PostDetailSchemaWithFlags
     */
    'location'?: LocationModelSchema;
    /**
     *
     * @type {Array<ContentTagSchema>}
     * @memberof PostDetailSchemaWithFlags
     */
    'contents': Array<ContentTagSchema>;
    /**
     *
     * @type {{ [key: string]: number; }}
     * @memberof PostDetailSchemaWithFlags
     */
    'reactions'?: {
        [key: string]: number;
    };
    /**
     *
     * @type {string}
     * @memberof PostDetailSchemaWithFlags
     */
    'self_reaction'?: string;
    /**
     *
     * @type {boolean}
     * @memberof PostDetailSchemaWithFlags
     */
    'is_save': boolean;
    /**
     *
     * @type {{ [key: string]: number; }}
     * @memberof PostDetailSchemaWithFlags
     */
    'mentioned_users'?: {
        [key: string]: number;
    };
}
