/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AppsPostsShemasPostTagUserSchema } from './apps-posts-shemas-post-tag-user-schema';
import type { ContentsInner } from './contents-inner';
import type { LocationSearchSchema } from './location-search-schema';
/**
 *
 * @export
 * @interface PostCreateSchema
 */
export interface PostCreateSchema {
    /**
     *
     * @type {string}
     * @memberof PostCreateSchema
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof PostCreateSchema
     */
    tag_color: string;
    /**
     *
     * @type {boolean}
     * @memberof PostCreateSchema
     */
    full_size_mode?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PostCreateSchema
     */
    share_to_vk?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PostCreateSchema
     */
    likes_visible?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PostCreateSchema
     */
    share_enable: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PostCreateSchema
     */
    comments_enable?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PostCreateSchema
     */
    reactions_enable?: boolean;
    /**
     *
     * @type {Array<ContentsInner>}
     * @memberof PostCreateSchema
     */
    contents: Array<ContentsInner>;
    /**
     * Location.
     * @type {LocationSearchSchema}
     * @memberof PostCreateSchema
     */
    location?: LocationSearchSchema;
    /**
     * ID of all tagged users.
     * @type {Array<AppsPostsShemasPostTagUserSchema>}
     * @memberof PostCreateSchema
     */
    tag_people?: Array<AppsPostsShemasPostTagUserSchema>;
    /**
     *
     * @type {number}
     * @memberof PostCreateSchema
     */
    aspect_ratio: number;
    /**
     *
     * @type {number}
     * @memberof PostCreateSchema
     */
    height: number;
    /**
     *
     * @type {boolean}
     * @memberof PostCreateSchema
     */
    is_draft?: boolean;
    /**
     * Draft settings.
     * @type {object}
     * @memberof PostCreateSchema
     */
    configuration?: object;
    /**
     *
     * @type {string}
     * @memberof PostCreateSchema
     */
    postpone?: string;
    /**
     *
     * @type {boolean}
     * @memberof PostCreateSchema
     */
    is_reel?: boolean;
}
