/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ContentModelDetailSchema } from './content-model-detail-schema';
/**
 *
 * @export
 * @interface PublicDocumentDetailModelSchema
 */
export interface PublicDocumentDetailModelSchema {
    /**
     *
     * @type {number}
     * @memberof PublicDocumentDetailModelSchema
     */
    id: number;
    /**
     *
     * @type {string}
     * @memberof PublicDocumentDetailModelSchema
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof PublicDocumentDetailModelSchema
     */
    readable_name: string;
    /**
     *
     * @type {ContentModelDetailSchema}
     * @memberof PublicDocumentDetailModelSchema
     */
    content: ContentModelDetailSchema;
}
