/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { UserAvatarFollowFlag } from './user-avatar-follow-flag';
/**
 *
 * @export
 * @interface ReactionSchemaWithUser
 */
export interface ReactionSchemaWithUser {
    /**
     *
     * @type {number}
     * @memberof ReactionSchemaWithUser
     */
    'id': number;
    /**
     * Specific reaction, which was putted (like | dislike | emoji)
     * @type {string}
     * @memberof ReactionSchemaWithUser
     */
    'action': string;
    /**
     *
     * @type {string}
     * @memberof ReactionSchemaWithUser
     */
    'created_at': string;
    /**
     *
     * @type {UserAvatarFollowFlag}
     * @memberof ReactionSchemaWithUser
     */
    'user': UserAvatarFollowFlag;
}
