/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ReadUrlWithSize } from './read-url-with-size';
/**
 *
 * @export
 * @interface ReadUrlAllSizes
 */
export interface ReadUrlAllSizes {
    /**
     *
     * @type {Array<ReadUrlWithSize>}
     * @memberof ReadUrlAllSizes
     */
    data: Array<ReadUrlWithSize>;
}
