/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Story
 */
export interface Story {
    /**
     *
     * @type {number}
     * @memberof Story
     */
    'id': number;
    /**
     *
     * @type {string}
     * @memberof Story
     */
    'deleted_at'?: string | null;
    /**
     *
     * @type {string}
     * @memberof Story
     */
    'created_at': string;
    /**
     * Кому разрешено репостить сторис
     * @type {string}
     * @memberof Story
     */
    'reply_permission'?: string;
    /**
     *
     * @type {any}
     * @memberof Story
     */
    'configuration'?: any;
}
