/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ReadUrlSchema } from './read-url-schema';
/**
 *
 * @export
 * @interface SubSchemaUser
 */
export interface SubSchemaUser {
    /**
     *
     * @type {number}
     * @memberof SubSchemaUser
     */
    'id': number;
    /**
     *
     * @type {string}
     * @memberof SubSchemaUser
     */
    'account_id': string;
    /**
     *
     * @type {string}
     * @memberof SubSchemaUser
     */
    'username': string;
    /**
     *
     * @type {string}
     * @memberof SubSchemaUser
     */
    'profile_photo'?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof SubSchemaUser
     */
    'available_sizes'?: Array<string>;
    /**
     *
     * @type {Array<ReadUrlSchema>}
     * @memberof SubSchemaUser
     */
    'read_urls'?: Array<ReadUrlSchema>;
}
