/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { UploadedUrlSchema } from './uploaded-url-schema';
/**
 *
 * @export
 * @interface UploadUrls
 */
export interface UploadUrls {
    /**
     *
     * @type {Array<UploadedUrlSchema>}
     * @memberof UploadUrls
     */
    data: Array<UploadedUrlSchema>;
}
