/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ContentModelDetailWithoutThumbnail } from './content-model-detail-without-thumbnail';
/**
 *
 * @export
 * @interface UserWithFollowIndicators
 */
export interface UserWithFollowIndicators {
    /**
     *
     * @type {string}
     * @memberof UserWithFollowIndicators
     */
    'deleted_at'?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserWithFollowIndicators
     */
    'updated_at'?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserWithFollowIndicators
     */
    'created_at': string;
    /**
     *
     * @type {number}
     * @memberof UserWithFollowIndicators
     */
    'id': number;
    /**
     *
     * @type {string}
     * @memberof UserWithFollowIndicators
     */
    'name'?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserWithFollowIndicators
     */
    'username': string;
    /**
     *
     * @type {string}
     * @memberof UserWithFollowIndicators
     */
    'birthday'?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserWithFollowIndicators
     */
    'sex'?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserWithFollowIndicators
     */
    'bio'?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserWithFollowIndicators
     */
    'link'?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserWithFollowIndicators
     */
    'user_type': string;
    /**
     *
     * @type {boolean}
     * @memberof UserWithFollowIndicators
     */
    'is_active'?: boolean;
    /**
     *
     * @type {string}
     * @memberof UserWithFollowIndicators
     */
    'profession'?: string | null;
    /**
     * Account if private (for followers only)
     * @type {boolean}
     * @memberof UserWithFollowIndicators
     */
    'is_private'?: boolean;
    /**
     * Uuid of user in auth service.
     * @type {string}
     * @memberof UserWithFollowIndicators
     */
    'account_id'?: string | null;
    /**
     * Verified badge
     * @type {boolean}
     * @memberof UserWithFollowIndicators
     */
    'verified'?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof UserWithFollowIndicators
     */
    'is_follow': boolean;
    /**
     *
     * @type {boolean}
     * @memberof UserWithFollowIndicators
     */
    'is_follower': boolean;
    /**
     *
     * @type {boolean}
     * @memberof UserWithFollowIndicators
     */
    'is_follow_request_sent': boolean;
    /**
     *
     * @type {ContentModelDetailWithoutThumbnail}
     * @memberof UserWithFollowIndicators
     */
    'profile_photo'?: ContentModelDetailWithoutThumbnail;
}
