/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ContentModelDetailWithoutThumbnail } from './content-model-detail-without-thumbnail';
/**
 *
 * @export
 * @interface UserAvatarFollowFlag
 */
export interface UserAvatarFollowFlag {
    /**
     *
     * @type {number}
     * @memberof UserAvatarFollowFlag
     */
    'id': number;
    /**
     *
     * @type {string}
     * @memberof UserAvatarFollowFlag
     */
    'name'?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserAvatarFollowFlag
     */
    'username': string;
    /**
     * Uuid of user in auth service.
     * @type {string}
     * @memberof UserAvatarFollowFlag
     */
    'account_id'?: string | null;
    /**
     *
     * @type {ContentModelDetailWithoutThumbnail}
     * @memberof UserAvatarFollowFlag
     */
    'profile_photo'?: ContentModelDetailWithoutThumbnail;
    /**
     *
     * @type {boolean}
     * @memberof UserAvatarFollowFlag
     */
    'is_follow'?: boolean;
}
