/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ViewContentsSchema
 */
export interface ViewContentsSchema {
    /**
     *
     * @type {number}
     * @memberof ViewContentsSchema
     */
    'author_id': number;
    /**
     *
     * @type {number}
     * @memberof ViewContentsSchema
     */
    'object_id': number;
    /**
     *
     * @type {Array<number>}
     * @memberof ViewContentsSchema
     */
    'content_ids': Array<number>;
}
