/**
 * YUCO Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface SJBConnectRequest
 */
export interface SJBConnectRequest {
    /**
     *
     * @type {string}
     * @memberof SJBConnectRequest
     */
    'client': string;
    /**
     *
     * @type {string}
     * @memberof SJBConnectRequest
     */
    'encoding': SJBConnectRequestEncodingEnum;
    /**
     *
     * @type {string}
     * @memberof SJBConnectRequest
     */
    'protocol': SJBConnectRequestProtocolEnum;
    /**
     *
     * @type {string}
     * @memberof SJBConnectRequest
     */
    'transport': SJBConnectRequestTransportEnum;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof SJBConnectRequest
     */
    'data': {
        [key: string]: string;
    };
}
export declare const SJBConnectRequestEncodingEnum: {
    readonly Json: "json";
};
export type SJBConnectRequestEncodingEnum = typeof SJBConnectRequestEncodingEnum[keyof typeof SJBConnectRequestEncodingEnum];
export declare const SJBConnectRequestProtocolEnum: {
    readonly Json: "json";
};
export type SJBConnectRequestProtocolEnum = typeof SJBConnectRequestProtocolEnum[keyof typeof SJBConnectRequestProtocolEnum];
export declare const SJBConnectRequestTransportEnum: {
    readonly Websocket: "websocket";
};
export type SJBConnectRequestTransportEnum = typeof SJBConnectRequestTransportEnum[keyof typeof SJBConnectRequestTransportEnum];
