/**
 * YUCO Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { JwtTokenSchema } from './jwt-token-schema';
import type { UserModelSchema } from './user-model-schema';
/**
 *
 * @export
 * @interface UserWithTokens
 */
export interface UserWithTokens {
    /**
     *
     * @type {UserModelSchema}
     * @memberof UserWithTokens
     */
    'user': UserModelSchema;
    /**
     *
     * @type {JwtTokenSchema}
     * @memberof UserWithTokens
     */
    'tokens': JwtTokenSchema;
}
