/**
 * YUCO Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UserUpdateSchema
 */
export interface UserUpdateSchema {
    /**
     *
     * @type {string}
     * @memberof UserUpdateSchema
     */
    'id': string;
    /**
     *
     * @type {string}
     * @memberof UserUpdateSchema
     */
    'avatar'?: string;
    /**
     *
     * @type {string}
     * @memberof UserUpdateSchema
     */
    'username'?: string;
}
