/**
 * Yuco Notifications
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AxiosInstance } from 'axios';
import { DefaultApiInterface } from './api/default-api';
export interface YucoNotificationsApiGetterInterface {
    getDefaultApi: () => DefaultApiInterface;
}
export declare const yucoNotificationsConfigureGetter: (applyInterceptors: <T>(apiCreator: (axios: AxiosInstance) => T) => T) => YucoNotificationsApiGetterInterface;
