/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AxiosConfiguration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import { type RequestArgs, BaseAPI } from '../base';
import type { AdvertisementProfileCreateSchema } from '../model';
import type { AdvertisementProfileDetailSchema } from '../model';
import type { AdvertisementProfileNotifySettingsSchema } from '../model';
import type { AdvertisementProfileUpdateSchema } from '../model';
/**
 * AdvertisementProfilesApi - axios parameter creator
 * @export
 */
export declare const AdvertisementProfilesApiAxiosParamCreator: (configuration?: AxiosConfiguration) => {
    /**
     *
     * @summary Create Profile View
     * @param {AdvertisementProfileCreateSchema} advertisementProfileCreateSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createProfileViewPost: (advertisementProfileCreateSchema: AdvertisementProfileCreateSchema, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Get Advertisement Profile View
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAdvertisementProfileViewGet: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Update Notificiation Settings View
     * @param {AdvertisementProfileNotifySettingsSchema} advertisementProfileNotifySettingsSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateNotificiationSettingsViewPatch: (advertisementProfileNotifySettingsSchema: AdvertisementProfileNotifySettingsSchema, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Update Profile View
     * @param {AdvertisementProfileUpdateSchema} advertisementProfileUpdateSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateProfileViewPatch: (advertisementProfileUpdateSchema: AdvertisementProfileUpdateSchema, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * AdvertisementProfilesApi - functional programming interface
 * @export
 */
export declare const AdvertisementProfilesApiFp: (configuration?: AxiosConfiguration) => {
    /**
     *
     * @summary Create Profile View
     * @param {AdvertisementProfileCreateSchema} advertisementProfileCreateSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createProfileViewPost(advertisementProfileCreateSchema: AdvertisementProfileCreateSchema, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdvertisementProfileDetailSchema>>;
    /**
     *
     * @summary Get Advertisement Profile View
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAdvertisementProfileViewGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdvertisementProfileDetailSchema>>;
    /**
     *
     * @summary Update Notificiation Settings View
     * @param {AdvertisementProfileNotifySettingsSchema} advertisementProfileNotifySettingsSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateNotificiationSettingsViewPatch(advertisementProfileNotifySettingsSchema: AdvertisementProfileNotifySettingsSchema, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdvertisementProfileDetailSchema>>;
    /**
     *
     * @summary Update Profile View
     * @param {AdvertisementProfileUpdateSchema} advertisementProfileUpdateSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateProfileViewPatch(advertisementProfileUpdateSchema: AdvertisementProfileUpdateSchema, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdvertisementProfileDetailSchema>>;
};
/**
 * Request parameters for createProfileViewPost operation in AdvertisementProfilesApi.
 * @export
 * @interface AdvertisementProfilesApiCreateProfileViewPostRequest
 */
export interface AdvertisementProfilesApiCreateProfileViewPostRequest {
    /**
     *
     * @type {AdvertisementProfileCreateSchema}
     * @memberof AdvertisementProfilesApiCreateProfileViewPost
     */
    readonly advertisementProfileCreateSchema: AdvertisementProfileCreateSchema;
}
/**
 * Request parameters for updateNotificiationSettingsViewPatch operation in AdvertisementProfilesApi.
 * @export
 * @interface AdvertisementProfilesApiUpdateNotificiationSettingsViewPatchRequest
 */
export interface AdvertisementProfilesApiUpdateNotificiationSettingsViewPatchRequest {
    /**
     *
     * @type {AdvertisementProfileNotifySettingsSchema}
     * @memberof AdvertisementProfilesApiUpdateNotificiationSettingsViewPatch
     */
    readonly advertisementProfileNotifySettingsSchema: AdvertisementProfileNotifySettingsSchema;
}
/**
 * Request parameters for updateProfileViewPatch operation in AdvertisementProfilesApi.
 * @export
 * @interface AdvertisementProfilesApiUpdateProfileViewPatchRequest
 */
export interface AdvertisementProfilesApiUpdateProfileViewPatchRequest {
    /**
     *
     * @type {AdvertisementProfileUpdateSchema}
     * @memberof AdvertisementProfilesApiUpdateProfileViewPatch
     */
    readonly advertisementProfileUpdateSchema: AdvertisementProfileUpdateSchema;
}
/**
 * AdvertisementProfilesApi - interface
 * @export
 * @interface AdvertisementProfilesApi
 */
export interface AdvertisementProfilesApiInterface {
    /**
     *
     * @summary Create Profile View
     * @param {AdvertisementProfileCreateSchema} advertisementProfileCreateSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdvertisementProfilesApiInterface
     */
    createProfileViewPost(requestParameters: AdvertisementProfilesApiCreateProfileViewPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<AdvertisementProfileDetailSchema>;
    /**
     *
     * @summary Get Advertisement Profile View
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdvertisementProfilesApiInterface
     */
    getAdvertisementProfileViewGet(options?: RawAxiosRequestConfig): AxiosPromise<AdvertisementProfileDetailSchema>;
    /**
     *
     * @summary Update Notificiation Settings View
     * @param {AdvertisementProfileNotifySettingsSchema} advertisementProfileNotifySettingsSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdvertisementProfilesApiInterface
     */
    updateNotificiationSettingsViewPatch(requestParameters: AdvertisementProfilesApiUpdateNotificiationSettingsViewPatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<AdvertisementProfileDetailSchema>;
    /**
     *
     * @summary Update Profile View
     * @param {AdvertisementProfileUpdateSchema} advertisementProfileUpdateSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdvertisementProfilesApiInterface
     */
    updateProfileViewPatch(requestParameters: AdvertisementProfilesApiUpdateProfileViewPatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<AdvertisementProfileDetailSchema>;
}
/**
 * AdvertisementProfilesApi - object-oriented interface
 * @export
 * @class AdvertisementProfilesApi
 * @extends {BaseAPI}
 */
export declare class AdvertisementProfilesApi extends BaseAPI implements AdvertisementProfilesApiInterface {
    /**
     *
     * @summary Create Profile View
     * @param {AdvertisementProfilesApiCreateProfileViewPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdvertisementProfilesApi
     */
    createProfileViewPost(requestParameters: AdvertisementProfilesApiCreateProfileViewPostRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<AdvertisementProfileDetailSchema, any>>;
    /**
     *
     * @summary Get Advertisement Profile View
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdvertisementProfilesApi
     */
    getAdvertisementProfileViewGet(options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<AdvertisementProfileDetailSchema, any>>;
    /**
     *
     * @summary Update Notificiation Settings View
     * @param {AdvertisementProfilesApiUpdateNotificiationSettingsViewPatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdvertisementProfilesApi
     */
    updateNotificiationSettingsViewPatch(requestParameters: AdvertisementProfilesApiUpdateNotificiationSettingsViewPatchRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<AdvertisementProfileDetailSchema, any>>;
    /**
     *
     * @summary Update Profile View
     * @param {AdvertisementProfilesApiUpdateProfileViewPatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdvertisementProfilesApi
     */
    updateProfileViewPatch(requestParameters: AdvertisementProfilesApiUpdateProfileViewPatchRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<AdvertisementProfileDetailSchema, any>>;
}
