/**
 * Yuco Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AxiosConfiguration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import { type RequestArgs, BaseAPI } from '../base';
import type { PublicDocumentDetailModelSchema } from '../model';
/**
 * PublicDocumentApi - axios parameter creator
 * @export
 */
export declare const PublicDocumentApiAxiosParamCreator: (configuration?: AxiosConfiguration) => {
    /**
     *
     * @summary Get Public Document
     * @param {string} name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPublicDocumentGet: (name: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * PublicDocumentApi - functional programming interface
 * @export
 */
export declare const PublicDocumentApiFp: (configuration?: AxiosConfiguration) => {
    /**
     *
     * @summary Get Public Document
     * @param {string} name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPublicDocumentGet(name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PublicDocumentDetailModelSchema>>;
};
/**
 * Request parameters for getPublicDocumentGet operation in PublicDocumentApi.
 * @export
 * @interface PublicDocumentApiGetPublicDocumentGetRequest
 */
export interface PublicDocumentApiGetPublicDocumentGetRequest {
    /**
     *
     * @type {string}
     * @memberof PublicDocumentApiGetPublicDocumentGet
     */
    readonly name: string;
}
/**
 * PublicDocumentApi - interface
 * @export
 * @interface PublicDocumentApi
 */
export interface PublicDocumentApiInterface {
    /**
     *
     * @summary Get Public Document
     * @param {string} name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PublicDocumentApiInterface
     */
    getPublicDocumentGet(requestParameters: PublicDocumentApiGetPublicDocumentGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<PublicDocumentDetailModelSchema>;
}
/**
 * PublicDocumentApi - object-oriented interface
 * @export
 * @class PublicDocumentApi
 * @extends {BaseAPI}
 */
export declare class PublicDocumentApi extends BaseAPI implements PublicDocumentApiInterface {
    /**
     *
     * @summary Get Public Document
     * @param {PublicDocumentApiGetPublicDocumentGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PublicDocumentApi
     */
    getPublicDocumentGet(requestParameters: PublicDocumentApiGetPublicDocumentGetRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<PublicDocumentDetailModelSchema, any>>;
}
