/**
 * Yuco Messenger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AxiosConfiguration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import { type RequestArgs, BaseAPI } from '../base';
import type { MSResponseReadUrl } from '../model';
import type { MSUploadUrls } from '../model';
import type { SJBFilenamesSchema } from '../model';
import type { SJBReadURL } from '../model';
/**
 * AttachmentApi - axios parameter creator
 * @export
 */
export declare const AttachmentApiAxiosParamCreator: (configuration?: AxiosConfiguration) => {
    /**
     *
     * @summary Generate Uploaded Urls
     * @param {SJBFilenamesSchema} sJBFilenamesSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    generateUploadedUrlsPost: (sJBFilenamesSchema: SJBFilenamesSchema, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * ## Get url for read file from object storage  Send file hash in body
     * @summary Get Read Url
     * @param {SJBReadURL} sJBReadURL
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getReadUrlPost: (sJBReadURL: SJBReadURL, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * AttachmentApi - functional programming interface
 * @export
 */
export declare const AttachmentApiFp: (configuration?: AxiosConfiguration) => {
    /**
     *
     * @summary Generate Uploaded Urls
     * @param {SJBFilenamesSchema} sJBFilenamesSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    generateUploadedUrlsPost(sJBFilenamesSchema: SJBFilenamesSchema, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MSUploadUrls>>;
    /**
     * ## Get url for read file from object storage  Send file hash in body
     * @summary Get Read Url
     * @param {SJBReadURL} sJBReadURL
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getReadUrlPost(sJBReadURL: SJBReadURL, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MSResponseReadUrl>>;
};
/**
 * Request parameters for generateUploadedUrlsPost operation in AttachmentApi.
 * @export
 * @interface AttachmentApiGenerateUploadedUrlsPostRequest
 */
export interface AttachmentApiGenerateUploadedUrlsPostRequest {
    /**
     *
     * @type {SJBFilenamesSchema}
     * @memberof AttachmentApiGenerateUploadedUrlsPost
     */
    readonly sJBFilenamesSchema: SJBFilenamesSchema;
}
/**
 * Request parameters for getReadUrlPost operation in AttachmentApi.
 * @export
 * @interface AttachmentApiGetReadUrlPostRequest
 */
export interface AttachmentApiGetReadUrlPostRequest {
    /**
     *
     * @type {SJBReadURL}
     * @memberof AttachmentApiGetReadUrlPost
     */
    readonly sJBReadURL: SJBReadURL;
}
/**
 * AttachmentApi - interface
 * @export
 * @interface AttachmentApi
 */
export interface AttachmentApiInterface {
    /**
     *
     * @summary Generate Uploaded Urls
     * @param {SJBFilenamesSchema} sJBFilenamesSchema
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttachmentApiInterface
     */
    generateUploadedUrlsPost(requestParameters: AttachmentApiGenerateUploadedUrlsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<MSUploadUrls>;
    /**
     * ## Get url for read file from object storage  Send file hash in body
     * @summary Get Read Url
     * @param {SJBReadURL} sJBReadURL
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttachmentApiInterface
     */
    getReadUrlPost(requestParameters: AttachmentApiGetReadUrlPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<MSResponseReadUrl>;
}
/**
 * AttachmentApi - object-oriented interface
 * @export
 * @class AttachmentApi
 * @extends {BaseAPI}
 */
export declare class AttachmentApi extends BaseAPI implements AttachmentApiInterface {
    /**
     *
     * @summary Generate Uploaded Urls
     * @param {AttachmentApiGenerateUploadedUrlsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttachmentApi
     */
    generateUploadedUrlsPost(requestParameters: AttachmentApiGenerateUploadedUrlsPostRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<MSUploadUrls, any>>;
    /**
     * ## Get url for read file from object storage  Send file hash in body
     * @summary Get Read Url
     * @param {AttachmentApiGetReadUrlPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttachmentApi
     */
    getReadUrlPost(requestParameters: AttachmentApiGetReadUrlPostRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<MSResponseReadUrl, any>>;
}
