/**
 * YUCO Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ChangeLoginSchema
 */
export interface ChangeLoginSchema {
    /**
     *
     * @type {string}
     * @memberof ChangeLoginSchema
     */
    code?: string;
    /**
     *
     * @type {string}
     * @memberof ChangeLoginSchema
     */
    new_login?: string;
    /**
     *
     * @type {string}
     * @memberof ChangeLoginSchema
     */
    code_new_device?: string;
    /**
     *
     * @type {boolean}
     * @memberof ChangeLoginSchema
     */
    is_agreed?: boolean;
}
