/**
 * YUCO Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { JwtTokenSchema } from './jwt-token-schema';
/**
 *
 * @export
 * @interface TokensWithDetail
 */
export interface TokensWithDetail {
    /**
     *
     * @type {string}
     * @memberof TokensWithDetail
     */
    'detail': string;
    /**
     *
     * @type {JwtTokenSchema}
     * @memberof TokensWithDetail
     */
    'tokens': JwtTokenSchema;
}
