/**
 * YUCO Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Id } from './id';
/**
 *
 * @export
 * @interface UserInfoSchema
 */
export interface UserInfoSchema {
    /**
     *
     * @type {Id}
     * @memberof UserInfoSchema
     */
    'id': Id;
    /**
     *
     * @type {string}
     * @memberof UserInfoSchema
     */
    'username': string;
    /**
     *
     * @type {string}
     * @memberof UserInfoSchema
     */
    'email'?: string;
    /**
     *
     * @type {string}
     * @memberof UserInfoSchema
     */
    'phone'?: string;
    /**
     *
     * @type {string}
     * @memberof UserInfoSchema
     */
    'apple_name'?: string;
    /**
     *
     * @type {string}
     * @memberof UserInfoSchema
     */
    'google_name'?: string;
    /**
     *
     * @type {string}
     * @memberof UserInfoSchema
     */
    'google_avatar'?: string;
    /**
     *
     * @type {boolean}
     * @memberof UserInfoSchema
     */
    'have_password'?: boolean;
}
