/**
 * Yuco Messenger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { FileTypeChoices } from './file-type-choices';
/**
 *
 * @export
 * @interface MSAttachment
 */
export interface MSAttachment {
    /**
     *
     * @type {string}
     * @memberof MSAttachment
     */
    hashname: string;
    /**
     *
     * @type {string}
     * @memberof MSAttachment
     */
    thumbnail_hashname?: string;
    /**
     *
     * @type {FileTypeChoices}
     * @memberof MSAttachment
     */
    object_type: FileTypeChoices;
    /**
     *
     * @type {string}
     * @memberof MSAttachment
     */
    file_name: string;
    /**
     *
     * @type {number}
     * @memberof MSAttachment
     */
    size: number;
}
