/**
 * Yuco Messenger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Chat } from './chat';
/**
 *
 * @export
 * @interface MSChatBase
 */
export interface MSChatBase {
    /**
     *
     * @type {string}
     * @memberof MSChatBase
     */
    'title': string;
    /**
     *
     * @type {string}
     * @memberof MSChatBase
     */
    'uuid': string;
    /**
     *
     * @type {string}
     * @memberof MSChatBase
     */
    'icon_hashname'?: string;
    /**
     *
     * @type {string}
     * @memberof MSChatBase
     */
    'created_at': string;
    /**
     *
     * @type {string}
     * @memberof MSChatBase
     */
    'updated_at': string;
    /**
     *
     * @type {Chat}
     * @memberof MSChatBase
     */
    'type': Chat;
}
