/**
 * Yuco Messenger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { MSAttachment } from './msattachment';
import type { MSUser } from './msuser';
import type { Reactions } from './reactions';
import type { SourceMessage1 } from './source-message1';
/**
 * Full data of message
 * @export
 * @interface MSFullMessage
 */
export interface MSFullMessage {
    /**
     *
     * @type {{ [key: string]: Reactions; }}
     * @memberof MSFullMessage
     */
    'reactions'?: {
        [key: string]: Reactions;
    };
    /**
     *
     * @type {string}
     * @memberof MSFullMessage
     */
    'self_reaction'?: string;
    /**
     *
     * @type {boolean}
     * @memberof MSFullMessage
     */
    'is_read'?: boolean;
    /**
     *
     * @type {MSUser}
     * @memberof MSFullMessage
     */
    'forward_sender'?: MSUser;
    /**
     *
     * @type {SourceMessage1}
     * @memberof MSFullMessage
     */
    'source_message'?: SourceMessage1;
    /**
     *
     * @type {Array<MSAttachment>}
     * @memberof MSFullMessage
     */
    'attachments'?: Array<MSAttachment>;
    /**
     *
     * @type {MSUser}
     * @memberof MSFullMessage
     */
    'sender'?: MSUser;
    /**
     *
     * @type {string}
     * @memberof MSFullMessage
     */
    'uuid': string;
    /**
     *
     * @type {boolean}
     * @memberof MSFullMessage
     */
    'edited': boolean;
    /**
     *
     * @type {string}
     * @memberof MSFullMessage
     */
    'cache_id': string;
    /**
     *
     * @type {string}
     * @memberof MSFullMessage
     */
    'message'?: string;
    /**
     *
     * @type {string}
     * @memberof MSFullMessage
     */
    'account_uuid': string;
    /**
     *
     * @type {number}
     * @memberof MSFullMessage
     */
    'object_uuid'?: number;
    /**
     *
     * @type {string}
     * @memberof MSFullMessage
     */
    'object_type'?: string;
    /**
     *
     * @type {string}
     * @memberof MSFullMessage
     */
    'created_at': string;
    /**
     *
     * @type {string}
     * @memberof MSFullMessage
     */
    'updated_at': string;
    /**
     *
     * @type {string}
     * @memberof MSFullMessage
     */
    'deleted_at'?: string;
    /**
     *
     * @type {string}
     * @memberof MSFullMessage
     */
    'chat_uuid': string;
    /**
     *
     * @type {string}
     * @memberof MSFullMessage
     */
    'fw_source_message'?: string;
    /**
     *
     * @type {string}
     * @memberof MSFullMessage
     */
    'fw_source_account_uuid'?: string;
}
