/**
 * Yuco Messenger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { SizeType } from './size-type';
/**
 *
 * @export
 * @interface MSReadURL
 */
export interface MSReadURL {
    /**
     *
     * @type {string}
     * @memberof MSReadURL
     */
    'url': string;
    /**
     *
     * @type {SizeType}
     * @memberof MSReadURL
     */
    'size_type': SizeType;
}
