/**
 * Yuco Messenger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Period
 */
export interface Period {
    /**
     *
     * @type {string}
     * @memberof Period
     */
    since: string;
    /**
     *
     * @type {string}
     * @memberof Period
     */
    till: string;
}
