/**
 * Yuco Messenger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * An enumeration.
 * @export
 * @enum {string}
 */
export declare const SizeType: {
    readonly Original: "original";
    readonly Medium: "medium";
    readonly Small: "small";
};
export type SizeType = typeof SizeType[keyof typeof SizeType];
