/**
 * Yuco Messenger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ContentCreateSchema } from './content-create-schema';
import type { SubSchemaMessageObject } from './sub-schema-message-object';
/**
 *
 * @export
 * @interface SJBCreateMessage
 */
export interface SJBCreateMessage {
    /**
     *
     * @type {string}
     * @memberof SJBCreateMessage
     */
    'chat_id': string;
    /**
     *
     * @type {string}
     * @memberof SJBCreateMessage
     */
    'cache_id': string;
    /**
     *
     * @type {string}
     * @memberof SJBCreateMessage
     */
    'message'?: string;
    /**
     *
     * @type {Array<ContentCreateSchema>}
     * @memberof SJBCreateMessage
     */
    'attachments'?: Array<ContentCreateSchema>;
    /**
     *
     * @type {SubSchemaMessageObject}
     * @memberof SJBCreateMessage
     */
    'object'?: SubSchemaMessageObject;
}
