/**
 * Yuco Messenger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { SubSchemaForwardMessage } from './sub-schema-forward-message';
/**
 *
 * @export
 * @interface SJBForwardMessages
 */
export interface SJBForwardMessages {
    /**
     *
     * @type {string}
     * @memberof SJBForwardMessages
     */
    chat_uuid: string;
    /**
     *
     * @type {string}
     * @memberof SJBForwardMessages
     */
    message?: string;
    /**
     *
     * @type {string}
     * @memberof SJBForwardMessages
     */
    cache_id?: string;
    /**
     *
     * @type {Array<SubSchemaForwardMessage>}
     * @memberof SJBForwardMessages
     */
    forward_messages: Array<SubSchemaForwardMessage>;
}
