/**
 * Yuco Messenger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { MuteTypeEnum } from './mute-type-enum';
import type { Period } from './period';
/**
 *
 * @export
 * @interface SJBMute
 */
export interface SJBMute {
    /**
     *
     * @type {MuteTypeEnum}
     * @memberof SJBMute
     */
    type: MuteTypeEnum;
    /**
     *
     * @type {Period}
     * @memberof SJBMute
     */
    period?: Period;
}
