/**
 * Yuco Messenger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface SubSchemaForwardMessage
 */
export interface SubSchemaForwardMessage {
    /**
     *
     * @type {string}
     * @memberof SubSchemaForwardMessage
     */
    'uuid': string;
    /**
     *
     * @type {string}
     * @memberof SubSchemaForwardMessage
     */
    'cache_id': string;
}
